### ISSUE TITLE
What is the correct way to introduce custom code generator for anvil running in KSP mode?

### ISSUE THREAD

**Issue by IlyaGulya** [square/anvil#1010]
Previously we've had to implement `CodeGenerator` and provide it with `@AutoService(CodeGenerator::class)`

Do we now just implement regular KSP processor and apply it as any other?

**Comment by IlyaGulya** [comment]
I've made a KSP processor, it seems to be working just fine.
I will not close this issue, in case you have some concerns 🙂

**Comment by matejdro** [comment]
Does that mean that custom code generators for Anvil are now deprecated?

**Comment by RBusarow** [comment]
Not at all.

**Comment by matejdro** [comment]
So, approach from poster above is not correct?

**Comment by IlyaGulya** [comment]
> So, approach from poster above is not correct?

No, if you're using Anvil in KSP mode, you will need KSP processor. 
Otherwise you will need a regular anvil code generator.

**Comment by matejdro** [comment]
But I assume that eventually everything will be moving away from kapt to ksp? And then it will be deprecated?
