### ISSUE TITLE
Feature request: support methods annotated with `@ContributesAndroidInjector` 

### ISSUE THREAD

**Issue by quiro91** [square/anvil#102]
Currently Anvil generates `@Inject`, `@Provides` factories, but not code that Dagger Android generates for `@ContributesAndroidInjector`. The reason why I'm asking is that a lot of our feature module contains this annotation and it would be a great improvement to be able to remove kapt from those modules.

Would you consider supporting those? (I would be happy to contribute to this in case)

**Comment by vRallev** [comment]
I'm sorry, while this is a valid request I don't want to support that. Main reason is that Hilt pretty much replaces Dagger Android. We don't use it ourselves, so I'm less familiar and we wouldn't be able to catch regressions in our codebase.

**Comment by quiro91** [comment]
I can understand that. It might be worth for me to fork it and implement this feature.
