### ISSUE TITLE
Hints not getting propagated across JVM modules after upgrading to 2.5.0

### ISSUE THREAD

**Issue by madisp** [square/anvil#1078]
I've got something along the lines of this in one subproject:

```kotlin
@ContributesBinding(MyScope::class) @Singleton class SomeFoo @Inject constructor() : Foo
```

and a dependency on `Foo` in another subproject. I think this binding is forwarded via the `anvil.hints.*` code, however, it doesn't seem to get packaged in the subproject jar any more. `build/generated/ksp/main/kotlin` also used to be a source root in the IDE but is not any more. The build fails with the usual `error: [Dagger/MissingBinding] Foo cannot be provided without an ...`.

Versions / configuration:

- Gradle 8.11
- Anvil 2.5.0
- Kotlin 2.1.0
- `kapt.use.k2=true`
- `ksp.useKSP2=true`
- `com.squareup.anvil.trackSourceFiles=true`
- both the subproject with the binding / impl class and the consuming component are plain old JVM modules

Previous (working) Anvil version was 2.5.0-beta11

**Comment by JoelWilcox** [comment]
One clarification, did any other versions/settings change when upgrading to Anvil 2.5.0? The first thing that caught my eye was K2 kapt being enabled and that that might cause issues since Anvil doesn't support K2 yet and there could be some unexpected interop changes there. But if you already had the setting on with 2.5.0-beta11 then that seems less likely.

**Comment by madisp** [comment]
> One clarification, did any other versions/settings change when upgrading to Anvil 2.5.0? The first thing that caught my eye was K2 kapt being enabled and that that might cause issues since Anvil doesn't support K2 yet and there could be some unexpected interop changes there. But if you already had the setting on with 2.5.0-beta11 then that seems less likely.

Only Anvil version change + I did drop `useKsp(contributesAndFactoryGeneration = true)` config as it didn't exist on 2.5.0.

**Comment by RBusarow** [comment]
Anvil doesn't support KSP.  Those apis were experimental, but were no longer being developed.  They were removed in favor of Zac's fork: https://github.com/ZacSweers/anvil

Generated hints can be found in `<buildDir>/anvil/<source set name>/generated/anvil/hint/`.

The generated directory is not added as a source root in the IDE by default.  This decision was made to avoid a cycle where the generated files are processed twice ([context](https://github.com/square/anvil/pull/207#issuecomment-850768750)).  There is an option to enable the source mapping, called `syncGeneratedSources`.  It was added here: #412.

```kotlin
anvil {
  syncGeneratedSources = true
}
```

**Comment by madisp** [comment]
ah, that explains :) I'll switch to Zac's fork for now, will switch back once there's proper K2 support :)
