### ISSUE TITLE
Support for Kotlin IR Backend

### ISSUE THREAD

**Issue by ShikaSD** [square/anvil#11]
Kotlin 1.4 brings us new \*shiny\* IR backend which has it's own set of extensions for codegen. Current ones (`ExpressionCodegen` and the one for js) doesn't seem to be supported anymore.

Noticed it in practice while trying this with IR enabled. I know that it is a bit too early, but would be nice to have :)

**Comment by vRallev** [comment]
I have branches setup with Kotlin 1.4-M2 and they build fine. Do you know when this will start to break? Also note that IR has little value for this project, because Dagger is JVM only.

**Comment by ShikaSD** [comment]
I am not sure when this will be enabled by default, but it is supposed to be new default backend for all the platforms from my understanding. Maybe it is going to be enabled later, but afaik they target 1.4 as a release for this.

Regarding breaking it, I just had IR enabled on my testbed project, so that's why I have noticed it in the first place. As I mentioned, it is still quite early for this, but may become relevant closer to 1.4 release. :)

**Comment by vRallev** [comment]
Ah, I changed the title. I haven't tested with the new IR backend, yet.

**Comment by vRallev** [comment]
To enable the IR backend we can use the free compiler args and the `-Xuse-ir` flag.

**Comment by vRallev** [comment]
I changed the title to only support the IR backend. I heard that Kotlin 1.4 will be released without it and it'll be optional. It may be required for Kotlin 1.5.

**Comment by vRallev** [comment]
https://kotlinlang.org/docs/reference/whatsnew14.html#new-jvm-ir-backend
