### ISSUE TITLE
Kotlin 1.4.20 API incompatibility

### ISSUE THREAD

**Issue by stephanenicolas** [square/anvil#117]
Using kotlin 1.4.20 current master, I see the following issue:
(with AGP 4.2 C10, gradle 6.7 last nightly / RC)

```
e: java.lang.NoSuchMethodError: org.jetbrains.kotlin.descriptors.EffectiveVisibilityKt.effectiveVisibility$default(Lorg/jetbrains/kotlin/descriptors/ClassDescriptor;ZILjava/lang/Object;)Lorg/jetbrains/kotlin/descriptors/EffectiveVisibility;
        at com.squareup.anvil.compiler.InterfaceMerger$addSyntheticSupertypes$classes$3.invoke(InterfaceMerger.kt:59)
        at com.squareup.anvil.compiler.InterfaceMerger$addSyntheticSupertypes$classes$3.invoke(InterfaceMerger.kt:17)
```

**Comment by stephanenicolas** [comment]
To fix the issue, we will just have to rebuild anvil against 1.4.20, no other changes are needed.
But we need to build both the plugin and the compiler, I had forgotten to rebuild the compiler.

**Comment by vRallev** [comment]
That's normal with compiler plugins. This was the case for Kotlin 1.3 vs 1.4 as well. I don't think there's an action item.
