### ISSUE TITLE
@JvmSuppressWildcards is placed in the wrong position in generated membersInjector

### ISSUE THREAD

**Issue by quiro91** [square/anvil#125]
Given I have a class
```
class Box<T: CharSequence> @Inject constructor(val element: T)
```
and a second class where the first is injected:
```
class Fragment {
    @Inject lateinit var box: Box<String>
```
then I see a members injector generated as:
```
class Fragment_MembersInjector(
  private val param0: Provider<@JvmSuppressWildcards Box<String>>
) : MembersInjector<Fragment> {
```
but I think the position of `@JvmSuppressWildcards ` is incorrect and should be instead
```
class Fragment_MembersInjector(
  private val param0: Provider<Box<@JvmSuppressWildcards String>>
) : MembersInjector<Fragment> {
```

**Comment by vRallev** [comment]
Does it cause compile errors?

**Comment by quiro91** [comment]
I was trying to create a repro sample for this, but I ended up discovering another bug. So I opened #126, and in the meantime I will investigate this better

**Comment by vRallev** [comment]
Is this now resolved?

**Comment by quiro91** [comment]
I'm gonna need to double check this, I was getting an error from KAPT in a downstream module that used a module where Anvil was generating factories. I'll try it out as soon as I can

**Comment by quiro91** [comment]
I can confirm this compiles fine. Closing the issue.
