### ISSUE TITLE
Support @Inject constructor for internal classes injected in same gradle module

### ISSUE THREAD

**Issue by japplin** [square/anvil#146]
``` kotlin
internal class Bar @Inject constructor()
class Foo @Inject constructor(private val bar: Bar)
```
Results in :`'public' function exposes its 'internal' return type`

**Comment by vRallev** [comment]
That's expected. The `internal` modifier is misleading. In a multi-module project Dagger must access the type `Bar` outside of this module.

**Comment by japplin** [comment]
This combination compiles for me currently when using dagger kapt though

**Comment by vRallev** [comment]
Because Dagger ignores Kotlin visibility rules and generates Java. Anvil generates Kotlin code, which enforces the correct behavior.

**Comment by japplin** [comment]
Ah makes sense, thanks for clarifying.
