### ISSUE TITLE
Support including private dagger modules within same file

### ISSUE THREAD

**Issue by japplin** [square/anvil#148]
```kotlin
class Foo

class Bar(foo: Foo)

@Module(includes = [MyPrivateModule::class])
class MyPublicModule {
	@Provides fun bar(foo: Foo): Bar = Bar(foo)
}

@Module
private class MyPrivateModule {
	@Provides fun foo(): Foo = Foo()
}
```
Gives these errors:
`'public' function exposes its 'private' parameter type MyPrivateModule` 
 `Cannot access 'MyPrivateModule': it is private in file`

**Comment by vRallev** [comment]
Similar to the other issue. You expose `MyPrivateModule` in the annotation and Dagger will read this later. It's misleading.
