### ISSUE TITLE
Have a "generate Dagger factories only" mode

### ISSUE THREAD

**Issue by vRallev** [square/anvil#164]
One downside of Anvil is that it disables incremental compilation for the stub generating task. For some projects that could be a performance killer. At the same time, these projects would be interested in using the feature to [generate Dagger factories](https://github.com/square/anvil#experimental-dagger-factory-generation). For that we don't need to disable incremental compilation.

**Comment by ursusursus** [comment]
So, this is for the case where I want anvil to replace dagger kapt for compiling a `@Module`; but I **don't have** `@ContributesTo` on it?

**Comment by vRallev** [comment]
I'd suggest to use this mode ONLY in projects that never use `@ContributesTo`, but want to use Anvil for compiling `@Module`s to remove Kapt. I wouldn't switch this flag on and off for separate modules, the benefit wouldn't be worth the extra effort.

**Comment by ursusursus** [comment]
I see, thanks
