### ISSUE TITLE
Support AssistedInject

### ISSUE THREAD

**Issue by vRallev** [square/anvil#165]
Support generating the code that the [AssistedInject](https://github.com/square/AssistedInject) annotation processor would generate.

**Comment by mos8502** [comment]
With dagger recently introducing support for [AssitedInject](https://dagger.dev/dev-guide/assisted-injection) does this still make sense ?

**Comment by vRallev** [comment]
Anvil only needs to support Dagger's assisted inject. The Square library is pretty much obsolete right now.

**Comment by vRallev** [comment]
Created #182
