### ISSUE TITLE
Should throw error for incorrect module type

### ISSUE THREAD

**Issue by chrisjenx** [square/anvil#183]
Noticed that Anvil doesn't throw or fail when trying to do this, which subsequently caused dagger to fail downstream.

```
@Module
@ContributesTo(AppScope::class)
interface LibraryModule {
    @Provides
    fun providesSomeEndpoint(retrofit: Retrofit): SomeEndpoint = retrofit.create()
}
```

Not sure if Anvil should ignore this or throw an error?

**Comment by vRallev** [comment]
Does Dagger throw an error? I never tried this before.

**Comment by chrisjenx** [comment]
Ahh thanks for fixing! Was literally just following up on this when you closed it :+1:
