### ISSUE TITLE
Do away with @JvmStatic

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#184]
Hi,
Hilt seems to make attaching `@JvmStatic` to every provider method obsolete. 

Can we as well?

**Comment by vRallev** [comment]
That's a Dagger feature for a while now and not related to Hilt: https://github.com/google/dagger/releases/tag/dagger-2.26

You don't need `@JvmStatic` for Anvil either.

**Comment by ursusursus** [comment]
Well yes, but wasn't the idea of @JvmStatic that it allows the module instance to be optimized away by dagger?

**Comment by vRallev** [comment]
I'm not sure what you're asking for. Is there something that Dagger supports, but Anvil doesn't? Can you show me an example what you'd like to do, but doesn't work?
