### ISSUE TITLE
Ability to compose annotations

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#185]
Hi,
I have plugin framework enabled via multibinding.

I always need to attach all these annotations to make it work

```
@AppScopedInitialized
@IntoSet
@Provides
@JvmStatic
fun widgetUpdater(): Scoped...
```

This is error prone and tideous (Somebody always forgets the `@IntoSet` ). 

Would it be possible to add a custom `@MyCustomWhatever` annotation which would be a composition of those 4? (or abitrary in general) 

I tried at language level, but it seems that its not supported. Only if given framework (anvil) would provide such api. Spring seems to have `@AliasFor` https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/AliasFor.html

Would that be possible? It would unlock great new "scripting" ability

**Comment by vRallev** [comment]
Thanks for the suggestion, but I don't have high hopes for that feature. Anvil has a small API surface and it should stay slim if possible. The implementation could be tricky for certain qualifiers like `@MyQualifier(SomeScope::class)`. 

For now I'll close the ticket. But we could always revisit it if there's more demand.
