### ISSUE TITLE
ContributesBinding doesn't replace dependencies from ContributesTo module

### ISSUE THREAD

**Issue by naixx** [square/anvil#188]
Imagine we have a class 
`open class Navigator constructor(val activity: MainActivity) `
and we want to override it in a flavor.

We've created a module. The main flavor clearly has a scope
```
@Module
@ContributesTo(MainActivityScopeMarker::class)
object NavigatorModule {
    @Provides
    fun provideNavigator(activity: MainActivity): Navigator = Navigator (activity)
}
```

So in feature flavor, we are trying to replace it with
```
@ContributesBinding(MainActivityScopeMarker::class, replaces = [Navigator ::class], boundType = Navigator ::class)
class FeatureNavigator @Inject constructor(activity: MainActivity): Navigator (activity) {

    override fun show() {
...
    }
}
```
And anvil produces the error `Could not determine the scope of the replaced Navigator `, but we clearly have a scope on the module. We could apply `ContributesBinding` to the `Navigator`, but we can't without a bound type(and I don't want to introduce an interface, just replace implementation with another one)

So my question is, would it be possible to achieve desired behavior of replacing dependency using `ContributesBinding` without creating two modules with `ContributesTo`?

**Comment by vRallev** [comment]
I think if you change `replaces = [Navigator::class]` to `replaces = [NavigatorModule::class]`, then it should work.

**Comment by vRallev** [comment]
There's a test for this, too: https://github.com/square/anvil/blob/1bd03e885939a40bf3313f1a67b0de0178d43694/compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt#L257-L285

**Comment by naixx** [comment]
Thanks, it works
