### ISSUE TITLE
AssistedInject factory generation elides parameter nullability

### ISSUE THREAD

**Issue by jzbrooks** [square/anvil#189]
```kotlin
public class MemberDirectoryViewModel_Factory_Impl(
  private val delegateFactory: MemberDirectoryViewModel_Factory
) : MemberDirectoryViewModel.Factory {
  public override fun create(groupToken: String, group: Account.Group): MemberDirectoryViewModel =
      delegateFactory.get(groupToken, group)

  public companion object {
    @JvmStatic
    public fun create(delegateFactory: MemberDirectoryViewModel_Factory):
        Provider<MemberDirectoryViewModel.Factory> =
        InstanceFactory.create(MemberDirectoryViewModel_Factory_Impl(delegateFactory))
  }
}
```

Is generated from:

```kotlin
@AssistedFactory
interface Factory {
    fun create(groupToken: String?, group: Account.Group?): MemberDirectoryViewModel
}
```

Which causes:

```
e: [...]/MemberDirectoryViewModel_Factory_Impl.kt: (14, 8): Class 'MemberDirectoryViewModel_Factory_Impl' is not abstract and does not implement abstract member public abstract fun create(groupToken: String?, group: Account.Group?): MemberDirectoryViewModel defined in com.faithlife.mobile.memberdirectory.MemberDirectoryViewModel.Factory
e: [...]/MemberDirectoryViewModel_Factory_Impl.kt: (17, 10): 'create' overrides nothing
```

I'm eager to use the anvil dagger factory generation!

**Comment by vRallev** [comment]
Thanks for the sample. Yes, that needs to be supported.

**Comment by vRallev** [comment]
@jzbrooks I've published a snapshot release with the fix `2.0.13-SNAPSHOT`. Could you please confirm that the issue is gone before I push a new release? Thanks!

**Comment by jzbrooks** [comment]
It seems to have gotten past that point in compilation, but now I'm missing the dagger-generated component implementations. For component `ApplicationComponent`, we explicitly use `DaggerApplicationComponent` to set things up. The latter is missing.

**Comment by vRallev** [comment]
That is a separate known "issue". Anvil cannot generate the code for `@Component`. In these modules you still need to use the Dagger annotation processor. See https://github.com/square/anvil#dagger-factory-generation

> This feature can only be enabled in Gradle modules that don't compile any Dagger component. Since Anvil only processes Kotlin code, you shouldn't enable it in modules with mixed Kotlin / Java sources either.

However, Anvil should throw an error in this case: https://github.com/square/anvil/blob/main/compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ComponentDetectorCheck.kt

**Comment by jzbrooks** [comment]
Gotcha. Are there any plans to support modules with dagger components?

**Comment by vRallev** [comment]
No, because that's where the real Dagger magic happens. Replacing this single annotations means reimplementing the entire Dagger annotation processor.
