### ISSUE TITLE
Can the module contribute to more than one scope

### ISSUE THREAD

**Issue by sanginovs** [square/anvil#196]
Hi @vRallev, 
first of all, thanks a lot for this library. I am currently giving it a try and had a quick question. 
Can the dagger module contribute to more than one scope using Anvils `@ContributesTo(scope1, scope2)` annotation?
 I am running into this scenario in a multi-module Android project in which two separate Dagger components located in 2 different modules depend on `SharedPreferences` dagger module. 
 
```
 @ApplicationScope
@Component(
    modules = [SharedPrefsModule::class],
  
```

```
@FeatureScope
@Component(
    modules = [
        SharedPrefsModule::class
    ])
```
    
   
```
@Module
object SharedPrefsModule {
    @Provides 
    fun sharedPref(context: Context) : SharedPreferences = context.getSharedPreferences("name")
 }
```
 
 
 How would i migrate this using Anvil? Looks like @ContributesTo(scope: KClass<*>) cannot take multiple Anvil scopes.

**Comment by vRallev** [comment]
No, that isn't supported. However, you can still include this particular manually in the `@MergeComponent` annotation.

**Comment by sanginovs** [comment]
thank you @vRallev. will do

**Comment by bubenheimer** [comment]
Would it be possible to reconsider supporting this? My use case is a multi-process app with one component per process, 2 processes/components total. Modules may contribute to one component, or the other, or both. There are many modules for each of these three cases. I wish there was a way to incorporate Anvil here, but it does not seem very feasible at the moment.

**Comment by vRallev** [comment]
This will be part of #236 as soon as Kotlin 1.6 allows repeated annotations.
