### ISSUE TITLE
Anvil cannot generate the code for Dagger components or subcomponents. 

### ISSUE THREAD

**Issue by sanginovs** [square/anvil#197]
Hi @vRallev 

I am running into this issue with the library when i set `generateDaggerFactories = true`. 
Here's my example:
My FeedComponent uses Anvil and depends on CoreComponent which doesn't use Anvil. 
```
@FeedScope
@MergeComponent(
    scope = AnvilFeedScope::class,
    dependencies = [
        CoreComponent::class
    ]
)
interface FeedComponent { ...}
```

CoreComponent also depends on other components. 
```
@Singleton
@Component(
    dependencies = [
        ExampleComponent1::class,
        ExampleComponent2::class
    ],
    modules = [ ... ]
)
interface CoreComponent { .. }

```

Whenever I set `generateDaggerFactories = true` in feed's gradle file. I keep getting this error:
`Anvil cannot generate the code for Dagger components or subcomponents. In these cases the Dagger annotation processor is required. Enabling the Dagger annotation processor and turning on Anvil to generate Dagger factories is redundant. Set 'generateDaggerFactories' to false.`

Does that mean for it to work i need to migrate the CoreComponent and its dependent components into Anvil? Or it's just not possible to use `generateDaggerFactories = true` when the component has dependencies? If so, how would you suggest refactoring the code in order to be able to use `generateDaggerFactories`. The main advantage of Anvil is `generateDaggerFactories = true` since it reduces build time so i'd like to get this work. Appreciate your answer.

**Comment by vRallev** [comment]
It's just not possible to use `generateDaggerFactories = true` in modules that use `@Component`. I recommend to move components into separate modules. For example, our components live in the final app module. This app module uses Kapt, but all other library modules use Anvil and `generateDaggerFactories = true`.
