### ISSUE TITLE
Does generateDaggerFactories generate DaggerYourComponentName.builder() ?

### ISSUE THREAD

**Issue by sanginovs** [square/anvil#199]
Hi @vRallev 

I had question regarding `generateDaggerFactories`. We use Dagger 2 `@Component.Builder` and Dagger usually generates `DaggerYourComponentName` class during compile time. As a result, we access builder through that class: `DaggerYourComponentName.builder().build()` to create a component.
Now, whenever i enable `generateDaggerFactories` and disable dagger annotation processor, I am running into this error:
`Unresolved reference: DaggerYourAppComponentName`. 
I think this is because this class is usually generated by Dagger annotation processor and Anvil isn't generating it. 
But, if i include Dagger annotation processor and set `generateDaggerFactories=true`, I will get `conflicting className` error probably because both Anvil and Dagger annotation processor is generating its own version.

Example Code:
```
@Component(modules = [ ... ])
interface ExampleComponent {

    @Component.Builder
    interface Builder {
        fun build():  ExampleComponent
    }
    
    companion object { 
        @JvmStatic
        fun create(): ExampleComponent=
            DaggerExampleComponent.builder()
                .build()
                .also { component = it }
    }
}
```

Do you have any idea why this happens? 
Thank you so much for your help.

**Comment by vRallev** [comment]
You should not set `generateDaggerFactories=true` in a module that uses a `@Component` annotation. Keep using the Dagger annotation processor in this module. Also please don't create a separate issue for each question. I would have replied in #197.

**Comment by sanginovs** [comment]
@vRallev this is happening after i removed `@Component` and replaced it with `@MergeComponent`. Here's what i have:

```
@MergeComponentComponent(scope=AnvilExampleScope::class, modules = [ ... ])
interface ExampleComponent {

    @Component.Builder
    interface Builder {
        fun build():  ExampleComponent
    }
    
    companion object { 
        @JvmStatic
        fun create(): ExampleComponent=
            DaggerExampleComponent.builder()
                .build()
                .also { component = it }
    }
}
```

Will it not work if there's `@Component.Builder` annotation?

**Comment by vRallev** [comment]
`@MergeComponent` generates the `@Component` under the hood. It's still the same problem.

**Comment by sanginovs** [comment]
i see what you mean. i just tested it with your sample project and it's very helpful.
