### ISSUE TITLE
Support generating DaggerComponent

### ISSUE THREAD

**Issue by thegarlynch** [square/anvil#203]
The reason that i think this is needed is
1. Dagger didn't supply a mean to only generate a dagger component given factory for everything else
2. Aside from architecture benefits, Anvil is good at kotlinizing dagger and i think there is no other project coming from dagger to fix this
3. Kapt compiling back and forth stubbing java code to kotlin take such a time, it even exceeds regular kapt.
4. If you don't want to make it for anvil single responsibility reason, then could anvil have separated repositories just for dagger stub generation and we could move that in new repository

**Comment by vRallev** [comment]
I'd like to, but this would mean reimplementing the Dagger annotation processor entirely. When Dagger generates the component, then all the magic is happening and the majority of code is generated. Implementing that is a major effort and at this point we'd almost have Dagger 3 and could consider Kotlin specific design changes. It's not on our roadmap and we have no to plans to do that.
