### ISSUE TITLE
Scope name can be confusing

### ISSUE THREAD

**Issue by gabrielfeo** [square/anvil#213]
Anvil's API is very clear and simple. Calling the marker classes Scopes can be confusing though. This seems to be [acknowledged in the README](https://github.com/square/anvil#scopes).

**tl;dr** Would the team consider recommending another name for these marker classes, since there's another well-established concept in the Dagger/JSR-330 vocabulary with the same name? Maybe "Graph".

### May induce mistakes

When you're debugging a situation caused by forgetting to scope something. You may forget to scope at first, and later you may not notice that the scope marker is missing when skimming through the DI declarations.

```kotlin
@Scope annotation class ViewModelScoped // JSR-330 scope
abstract class ViewModelScope // Anvil scope

@ViewModelScoped // could forget to add this annotation
@MergeComponent(scope = ViewModelScope::class) // because you may think it's already scoped
interface ViewModelComponent

@ViewModelScoped // could forget to add this annotation
@ContributesBinding(ViewModelScope::class) // because you may think it's already scoped
class SomeViewModelImpl @Inject constructor() : SomeViewModel
```

### May lead to fragmentation

Developers who are uncomfortable with the repeated name may come up with alternatives for each project.

#### Call Anvil scopes a different name per-project

Not too bad since it's only a marker class, but following the official naming convention is usually preferable as it makes things easier to reason about.

```kotlin
@Scope annotation class ViewModelScope // JSR-330 scope
abstract class ViewModelGraph // Anvil scope

@ViewModelScope
@MergeComponent(scope = ViewModelGraph::class)
interface ViewModelComponent

@ViewModelScope
@ContributesBinding(ViewModelGraph::class)
class SomeViewModelImpl @Inject constructor() : SomeViewModel
```

#### Use the same class for both concepts

Use the same class for both JSR-330 scopes and Anvil scopes. This may have even worse potential for mistakes.

```kotlin
@Scope annotation class ViewModelScope // Both JSR-330 and Anvil scope

@ViewModelScope // Even more confusing now that only the way of attributing differs, not the name
@ContributesBinding(ViewModelScope::class)
class SomeViewModelImpl @Inject constructor() : SomeViewModel
```

**Comment by vRallev** [comment]
I share some of your concerns that the term "scope" is overloaded. But changing the term for Anvil will be a major shift I don't see it happening anytime soon. 

Anvil is flexible, it's up to you how you model your scopes and marker classes. For example, in our project we use one single scope annotation and use the marker classes to differentiate between different components:
```
@Scope annotation class SingleIn(
  val value: KClass<*>
)

@SingleIn(AppScope::class)
@ContributesTo(AppScope::class)
```

**Comment by gabrielfeo** [comment]
Thank you for your reply. I understand.

That's a good idea with `SingleIn`. It doesn't solve the naming issue, but it makes the concepts intuitive inside the project.
