### ISSUE TITLE
Interoperation with Hilt - Ability to get rid of kapt in most modules

### ISSUE THREAD

**Issue by matejdro** [square/anvil#214]
README clearly states that Anvil is not needed with Hilt, since Hilt already includes all Anvil's features.

However, Anvil has one huge advantage over Hilt: It does not use kapt, which makes it much lighter on the build speed.

Would it be possible to have Anvil's `ContributesTo` interop with Hilt's `InstallIn`? Most modules in our project only use `@Module` and `@Inject`. If Anvil would support that, we could get rid of Hilt annotation processor in most modules and only rely on lighter Anvil.

**Comment by vRallev** [comment]
There are no plans right now to improve interop. However, you might be able to use Anvil to some part. You could use Anvil's `ContributesTo` and then use `[@MergeModules](https://github.com/square/anvil/blob/main/annotations/src/main/java/com/squareup/anvil/annotations/compat/MergeModules.kt)` and this module you `InstallIn` in Hilt's graph. You can do the same with `[@MergeInterfaces](https://github.com/square/anvil/blob/main/annotations/src/main/java/com/squareup/anvil/annotations/compat/MergeInterfaces.kt)`. I've never tested it myself, but it could work.

**Comment by vRallev** [comment]
Let me know if there's any other question.

**Comment by mochadwi** [comment]
I think this article helps a lot to have a "companion" feature from Hilt with anvil https://dev.to/marcellogalhardo/n26-path-to-anvil-abd cc @matejdro

**Comment by matejdro** [comment]
Right, but from what I see this article only explain how to replace Hilt, not interop with it.

**Comment by vRallev** [comment]
No, there's no way except for you to create your own Kotlin compiler plugin and modify the source code (similar to what Anvil does in the compiler backend).
