### ISSUE TITLE
Preemptive fail compilation when Multibinding can not be added to a Component

### ISSUE THREAD

**Issue by marcellogalhardo** [square/anvil#220]
Consider the following scenario:

![image](https://user-images.githubusercontent.com/4348197/109775886-543d1480-7c02-11eb-9cb4-76380794b30b.png)

If `:app` module does not directly depend on `library1`, Dagger won't fail the compilation as a map multi-binding will be resolved at runtime by a `@MapKey` and at the same time, Anvil won't be able to contribute the multi-binding to `:app` component - which might cause a runtime exception. For cases where we don't use multi-binding, Dagger will detect a binding is missing and fail the compilation rightfully. If necessary I can provide a small reproducible sample.

It would be beneficial if Anvil could alert us about this situation in a preemptive way and fail the compilation to avoid runtime 
exceptions for Modules that have a valid contribution to scope, but the target `MergeComponent` can not be contributed to from that module. 

This situation already happens (with Dagger multi-binding + `@ContributesTo`), but this enhancement will be extra helpful when combined with the new `@ContributesMultibinding` from #152.

**Comment by vRallev** [comment]
It's unclear to me how Anvil should do that. Anvil cannot detect if a module is not on classpath, but it meant to be on the classpath. This decision to not include a module could be done purposefully. In fact, that's quite common when you have multiple applications. What should Anvil do if `library1` is an external dependency? 

Dagger has a similar issue, where you might forget to add a module containing the multibinding to the component. You'll find out at runtime. There's simply no safety for multibindings and Anvil can't fix that.

**Comment by marcellogalhardo** [comment]
Right, what I had in mind is as following:

- Each `@Contributes*` annotation contains a marker scope.
- Each `@Merge*` annotation contains a marker scope.
- Only modules in a build class-path are processed by Anvil.

We can't help with multi-binding safety itself, as you explained, but we could help with the marker intention. For example, we could check the following invariants:

- Given a `@Contributes*` to a marker scope, then all `@Merge*` with same marker scope should have that module in generated Dagger component.
- Given a module is not in the build path, then it should not be processed (e.g., a module used by a full app but not used by a sample app). This guarantees sample apps, testing replaces, and others would not be affected by the first invariant.

I thought about two ways of accomplish that:

- When processing and generating the modules and components, keep track to ensure all `@Contributes*` with a marker scope can be accessed / included into all `@Merge*` with a same marker scope.
- Keep a hint to the generated code and marker scope, and verify the final Dagger component include those classes.

Do you think any of those could be valid solutions?

**Comment by vRallev** [comment]
> Given a `@Contributes*` to a marker scope, all `@Merge*` with the same marker scope should have that module in the generated Dagger component.

But that's how Anvil works. If a module is missing, then it's a bug and not an invariant.

**Comment by marcellogalhardo** [comment]
Hm, so I might be missing something. I will create a small reproducible of what I'm facing in the next days and get back here.

**Comment by marcellogalhardo** [comment]
Hey @vRallev - I created a repository to reproduce what I'm saying here: [code here](https://github.com/marcellogalhardo/anvil-missing-modules). All relevant parts are flagged with `FIXME` but I will highlight the lines I believe it is most relevant:

1. [App depends on Feature1](https://github.com/marcellogalhardo/anvil-missing-modules/blob/master/app/build.gradle#L39).
2. [Feature1 depends on Library1](https://github.com/marcellogalhardo/anvil-missing-modules/blob/master/feature1/build.gradle#L38).
3. [Library1 contributes two modules, one of them: Library1FragmentModule which has multi-binding](https://github.com/marcellogalhardo/anvil-missing-modules/blob/master/library1/src/main/java/dev/marcellogalhardo/library1/Library1Fragment.kt#L30).
4. [Library1 is in the build path and includes Anvil plugin](https://github.com/marcellogalhardo/anvil-missing-modules/blob/master/library1/build.gradle#L4).
5. [Here is the important part: none of the two modules (independent of multi-binding) will be included in the `MergeComponent(AppScope)` inside `app` but compilation will succeed without any warnings](https://github.com/marcellogalhardo/anvil-missing-modules/blob/master/app/src/main/java/dev/marcellogalhardo/anvilmodulemissing/MainComponent.kt#L8).
6. [If we uncomment the `app/build.gradle#L41` it fixes the problem as app now has direct access to the module](https://github.com/marcellogalhardo/anvil-missing-modules/blob/master/app/build.gradle#L42).

My comment [here](https://github.com/square/anvil/issues/220#issuecomment-790388405) is related to step 5.

**Comment by vRallev** [comment]
The issue is that you use `implementation` instead of `api` dependencies. You're explicitly telling Gradle not to add any dependencies to the compile classpath of downstream projects. You're only adding the dependencies to the runtime classpath of your app. You're actually using `implementation` incorrectly, that's why you see this behavior. I suggest to take a look at this [guide](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies).

For example, in the feature module you have
```kotlin
@[Module ContributesTo(AppScope::class)]
interface Feature1FragmentModule
```
`AppScope` is coming from the base module. Since you expose the type to consumers, you should import the base module with an `api` dependency and not `implementation`. 

I'm sorry, but everything works as expected and it's an issue with your project.

**Comment by marcellogalhardo** [comment]
Hm, thank you for the reference link and your time in the discussion. I read it and I agree with you, I'm overusing `implementation` for almost everything and should be using `api` in this case. Thank you again.
