### ISSUE TITLE
Kotlin Multiplatform Support

### ISSUE THREAD

**Issue by gabrielfeo** [square/anvil#222]
Are there plans to support Kotlin Multiplatform projects?

**Comment by vRallev** [comment]
Anvil is built on top of Dagger. Dagger is a Java library for the JVM and Android. Before Dagger isn't multiplatform, Anvil can't support it.

**Comment by gabrielfeo** [comment]
I'm sorry, this is a poorly written issue. I realize I can't use Anvil from common code, but I'm trying to use it in JVM and Android-specific code, within a multiplatform project. Currently, if I try to apply the plugin, I get a compile error:

```
Caused by: org.gradle.api.GradleException: No supported plugins for Anvil found on project ':sample'.
Only Android and Java modules are supported for now.
```

The plugin checks for the `kotlin-jvm` and `kotlin-android` plugins and throws, but could it work in multiplatform projects targeting only JVM and Android if this check wasn't present? This sort of project doesn't apply those plugins, only `org.jetbrains.kotlin.multiplatform`.

```kotlin
plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("com.squareup.anvil")
}

kotlin {
    android()
    jvm()
    sourceSets {
        val jvmMain by getting {
            dependencies {
                implementation(Dagger.Core)
            }
        }
// ...
```

**Comment by vRallev** [comment]
Would you mind creating a full sample application to help me get started? A tiny project with only one JVM and one Android module with the multiplatform plugin would be enough. I'm unsure how much https://youtrack.jetbrains.com/issue/KT-27683 will be an issue, but I can take a look.

**Comment by abyrnes** [comment]
@vRallev Here's a sample app: https://github.com/abyrnes/AnvilKMPSample

**Comment by vRallev** [comment]
@abyrnes Could you please add some code in the shared folder and JVM / Android specific folders? Otherwise I can't test it properly. Thanks.

**Comment by abyrnes** [comment]
Done! Hopefully it's sufficient. Happy to add anything else if needed

**Comment by vRallev** [comment]
I'll let you know, thanks!

**Comment by vRallev** [comment]
https://github.com/square/anvil/releases/tag/v2.2.3 should support MP projects. Could anyone please verify or are there other remaining issues?
