### ISSUE TITLE
Is it possible to have unit test of a real Subcomponent in module where it is defined?

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#234]
Hi, I have trouble grasping, if at all possible, how to do integration tests with real dagger component when using anvil/modularized codebase

_If the test would live in the final :app module, then ofcourse no problem; (run kapt in the unit test, create TestAppComponent which only swaps out android dependencies, and all else is ready to go)_

but I have a hunch it would be better for integration tests of Foo domain should live in the :foo module, right?

If so, lets say it looks like this (there only exists the usual AppScope, and RegistrationScope which represents registration flow)

```
@ContributesTo(RegistrationScope::class)
@Module
object RegistrationModule {

	@Provides
	fun registationRetrofit(@BaseOkHttp baseOkHttp: OkHttpClient, @BaseRetrofit baseRetrofit: Retrofit, authManager: AuthManager) {
		val registrationOkHttp = baseOkHttp.newBuilder()
			.addInterceptor(RegistationExpiredInterceptor(authManager))
			.build()

		return baseRetrofit.newBuilder()
			.client(registrationOkHttp)
			.build()
	}

	@Provides
	fun registrationService(@RegistrationRetrofit retrofit): RegistrationService {
		return retrofit.create(RegistrationService::class)
	}
}
```

If :registration module could see anything, the integration test would look like this (In human words; if any of the registration endpoints returns 410, the whole registration flow/scope/data should be discarded/logged out)

```
@Test `if any registration api returns 410, logout registration session` {
	val appComponent = TestAppComponent.create()
	val regisrationSubComponent = appComponent.registrationSubcomponentFactory.create()
	val regisrationService = regisrationSubComponent.regisrationService

	//
	// MockWebserver to return 410
	regisrationService.whatever()

	asserThat(onboardingManager.isLoggedOut).isTrue()
}


@AppScope 
@MergeComponent(AppScope::class, exclude = [.. bunch of android modules]) 
interface TestAppComponent { 
    @Component.Factory 
    interface Factory { 
        fun create(): TestAppComponent 
    } 
}
```

But obviously it cannot see that .. or can it?
I think its worth to have the tests local to the module they're from, in case that module gets reused somewhere else but not sure how :/

However, is it even worth it? Since if I could somehow recreate the TestAppComponent within the :registration module, I still won't get the guarantee the final app will work together.. Or is this going too far? Should I just create the dependencies manually in :registration. And only have the "widest" integration tests with real graphs in the final :app module?

**Comment by vRallev** [comment]
I'm not sure what you're asking exactly. This doesn't seem to be related to Anvil, but rather normal Dagger. You can always create any kind of component in test source sets. I'm doing the same in the integration tests for Anvil.

**Comment by ursusursus** [comment]
Yes but no, I could go deeper in a bit, but I'm trying the :app level variant first but blocked on https://github.com/square/anvil/issues/235
