### ISSUE TITLE
Anvil doesn't merge the interface: Component is not abstract and does not override abstract method 

### ISSUE THREAD

**Issue by sanginovs** [square/anvil#239]
Hi there, 

I am running into this issue. Anvil merges modules but when i contribute an interface to scope, it results in this error:
`DaggerComponent is not abstract and does not override abstract method exampleMethod() in ExampleInterface`

Example code:
```
abstract class AnvilAppScope private constructor()


@ContributesTo(AnvilAppScope::class)
interface ExampleInterface {
    fun exampleMethod(): ExampleClass
}



@AppScope
@MergeComponent(
    scope = AnvilAppScope::class,
    modules = [AndroidInjectionModule::class],
    dependencies = [Component1::class, Component2::class]
)
interface AppComponent {

   @Component.Builder
    interface Builder { ... }
}
```

**Comment by vRallev** [comment]
Please provide a sample project.

**Comment by sanginovs** [comment]
Hi @vRallev 
I create this [sample project](https://github.com/sanginovs/test-app-dagger-hilt/blob/master/sampleLibrary/src/main/java/com/example/samplelibrary) but wasn't able to reproduce it here however I had question about field injection. 

As you can see in this sample project, I have this class: [SomeClass](https://github.com/sanginovs/test-app-dagger-hilt/blob/master/sampleLibrary/src/main/java/com/example/samplelibrary/SomeClass.kt) and this class requires field injection. 
```
class SomeClass {

    @Inject lateinit var sayHello: SayHello

    init {
         //DaggerSampleLibraryComponent.inject(this)
         //or
        //SomeInterface.inject(this)
    }
    fun what(): String {
        sayHello.hi()
        return "Hi"
    }
}
```

I also have this [SomeInterface](https://github.com/sanginovs/test-app-dagger-hilt/blob/master/sampleLibrary/src/main/java/com/example/samplelibrary/di/SomeInteface.kt) that contributes to AnvilScope:
```
@ContributesTo(AnvilAppScope::class)
interface SomeInteface {
    fun what(): SomeClass
    fun inject(someClass: SomeClass)
}
```
To tell Dagger that `SomeClass` requires field injection, we usually call `DaggerSampleLibraryComponent.inject(this)` inside init or onCreate. How would i call this if my `fun inject(someClass: SomeClass)` is in Anvil `SomeInterface`?
And here's my [component](https://github.com/sanginovs/test-app-dagger-hilt/blob/master/sampleLibrary/src/main/java/com/example/samplelibrary/di/SampleLibraryComponent.kt)

Currently I get `lateinit property sayHello has not been initialized` error but I can't call `SomeInterface.inject(this)` inside my init.

**Comment by vRallev** [comment]
Please have a look it in the README. The first example answers your question: https://github.com/square/anvil#anvil

**Comment by sanginovs** [comment]
@vRallev I do see that my interface methods have been generated in my component, but whenever i call **AppComponent.injectActivity(this)** and rerun, I get `Unresolved reference` error on `injectActivity`

**Comment by vRallev** [comment]
I suspect it's an issue in your code, because we do this quite a lot as well and don't see any problems. Without a sample that reproduces the problem there isn't much I can do.

**Comment by sanginovs** [comment]
@vRallev yep  Here's the sample project: 
[link](https://github.com/sanginovs/test-app-dagger-hilt/)
You will notice I'm calling `DaggerSampleLibraryComponent.inject(this)` inside [SomeClass](https://github.com/sanginovs/test-app-dagger-hilt/blob/master/sampleLibrary/src/main/java/com/example/samplelibrary/SomeClass.kt). When you run the project, it doesn't compile because of `Unresolved reference inject error`.

**Comment by vRallev** [comment]
You're trying to call a member function without having an object, similarly how you would call a static function. I changed the line to this and it works:
```kotlin
(DaggerSampleLibraryComponent.builder().build() as SomeInteface).inject(this)
```

**Comment by sanginovs** [comment]
great it works. thank you @vRallev. do you think it's worth adding this example to README?
`(AppComponent.builder().build() as ComponentInterface).injectActivity(this)`

**Comment by vRallev** [comment]
No, the first example in the README shows that. This code snippet is very specific to your sample.
