### ISSUE TITLE
Feature Request: Support generation-only mode

### ISSUE THREAD

**Issue by ZacSweers** [square/anvil#258]
Currently, factory generation can be enabled in isolation but not other types of non-transforming generation like `@Contributes*` APIs. Talked offline a bit, it would be nice if there was a way to enable this mode of anvil while still disabling transformation (which requires disabling incremental stub generation).

**Comment by vRallev** [comment]
Basically a mode that supports everything but `MergeComponent` and `MergeSubcomponent`. Then incremental stub generation doesn't need to be disabled.
