### ISSUE TITLE
Different behavior depending on the location of the SubComponent

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [square/anvil#262]
# First Scenario

https://github.com/guuilp/DaggerExperiment/tree/main

## app module
`Android Application`
`Dagger Component` (AppScope)
`Dagger SubComponent` (ViewModelScope)
`FragmentFactory` (AppScope)
`ViewModelFactory` (AppScope
`Activity`
 
## core-di module
abstract classes for `AppScope` and `ViewModelScope`, map keys for `Fragment` and `ViewModel`.

## feature module
Two fragments following some kind of clean architecture:

`Fragment` (AppScope) > `VM` (AppScope) > `UseCase` (ViewModelScope) > `Repository` (ViewModelScope).

## Build result
Success ✅ 

# Second scenario

https://github.com/guuilp/DaggerExperiment/tree/vmcomponent-on-coredi

The only difference in here is the location of the `SubComponent`: moved it from `app` to `core-di`.

## Build result
Failed 🔴 

```
/Users/guilherme.pereira/Documents/Projects/DaggerExperiment/app/build/tmp/kapt3/stubs/debug/com/github/guuilp/daggerexperiment/di/ApplicationComponent.java:8: error: [Dagger/MissingBinding] com.github.guuilp.feature.domain.FirstUseCase cannot be provided without an @Provides-annotated method.
public abstract interface ApplicationComponent {
                ^
      com.github.guuilp.feature.domain.FirstUseCase is injected at
          com.github.guuilp.feature.presentation.FirstViewModel(firstUseCase, …)
```

# Description
The first scenario seems awkward for me, since a `Component` can't see bindings declared on `SubComponent`, but the project is compiling successfully even though `UseCase` (SubComponent) is being injected on `VM` (Component).

When I move the `SubComponent` to `core-di` module, the build fails as expected.

I wanted your help to understand what I may be doing wrong or if there's a bug somewhere (Anvil or Dagger).

By the way, thanks for the project, it's really awesome!

**Comment by vRallev** [comment]
I believe you're running into #160, which isn't supported yet. Am I right?

**Comment by guilherme-pereira-ifood** [comment]
It seems to be related, but I'm not sure is the same issue.

When #160 is implemented, the build would fail in both of the scenarios I showed?

**Comment by vRallev** [comment]
Yes, I'd think so. Therefore closing as duplicate.
