### ISSUE TITLE
Support same name val on @MergeComponent as on @ContributesTo component

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#263]
```
@AppScope
@MergeComponent(AppScope::class)
interface AppComponent {
    @Component.Factory
    interface Factory {
        fun create(@BindsInstance context: Context): AppComponent
    }
}

@ContributesTo(AppScope::class)
interface PartialAppComponent1 {
    val somethingDifferent: SomethingDifferent
}

@ContributesTo(AppScope::class)
interface PartialAppComponent2 {
    val somethingDifferent: SomethingDifferent
}
```

This compiles fine.

However

```
@AppScope
@MergeComponent(AppScope::class)
interface AppComponent {
    val somethingDifferent: SomethingDifferent <----------
}

@ContributesTo(AppScope::class)
interface PartialAppComponent {
    val somethingDifferent: SomethingDifferent
}
```

This does not.  `'somethingDifferent' hides member of supertype 'PartialAppComponent' and needs 'override' modifier`

Granted its all interface it should work, no?

**Comment by vRallev** [comment]
It could be expensive to check all of the interfaces, so I'm hesitant to do that. I'm wondering why you need to add the val 2nd time?

**Comment by ursusursus** [comment]
All those components live in different modules (and the MergeComponent lives in topmost :app module)

I was mostly hinting at the fact since PartialAppComponent1 and PartialAppComponent2 can live with same name vals, then AppComponent could maybe as well, since its a interface

Should I refactor so the MergeComponent annotate component has no vals at all as a rule?

**Comment by vRallev** [comment]
Our final components have no vals or functions. We do everything through contributed component interfaces.

**Comment by ursusursus** [comment]
I see. 
Btw how do you deal with subcomponents then? Doesn't the MergeSubcomponent need to contain a Factory attached to it's parent?

```
@UserScope
@MergeSubcomponent(UserScope::class)
interface UserComponent {

    @ContributesTo(AppScope::class)
    interface ParentComponent {
        val userComponentFactory: Factory
    }

    @Subcomponent.Factory
    interface Factory {
        fun create(): UserComponent
    }
}
```

I need this to be visible in a submodule, and currently I workedaround it via stupid indirection, hence the vals on MergeComponent in the original post. TLDR; I need to create the UserComponent instance which is a subcomponent of AppComponent

**Comment by vRallev** [comment]
We actually don't use factories or component builders. I guess what would be great to have is
```kotlin
    @MergeSubcomponent.Factory
    interface Factory {
        fun create(): UserComponent
    }
```
Another reason we don't see this issue is that we [generate Dagger factories with Anvil](https://github.com/square/anvil#dagger-factory-generation). I suggest you do the same in your sub module, then it should work like you expect, because the error won't be thrown.

**Comment by ursusursus** [comment]
I do use that flag as well to not use kapt in submodules. Does it do something more?

How do you create subcomponents then? no subcomponents just top level components?

**Comment by vRallev** [comment]
Kapt for Dagger only needs to be enabled for `@MergeComponent`, but not `@MergeSubcomponent`. Therefore, you only need to enable Kapt in your app module. That means you can put your `UserComponent` into a library module and don't need enable Kapt.

We create subcomponents through abstract factory methods: https://dagger.dev/dev-guide/subcomponents.html#defining-subcomponents-with-abstract-factory-methods

**Comment by ursusursus** [comment]
Oh really? That'đ great thanks!

Btw @the factory methods .. if I read it correctly, its this?
```
@ContributesTo(AppScope::class)
interface ParentComponent {
    fun userComponent(userId: UserId) : UserComponent
}
```

**Comment by vRallev** [comment]
Yes, the former:
```
@ContributesTo(AppScope::class)
interface ParentComponent {
    fun userComponent(userId: UserId) : UserComponent
}
```

**Comment by ursusursus** [comment]
I tried moving the @MergeSubcomponent UserComponent into user module, that works as you said.

But I'm still trying to to create UserComponent instance in a differnt not-a-user module, via partial components

```
@ContributesTo(UserScope::class)
interface NotInUserModuleUserComponent {
    
    @ContributesTo(AppScope::class)
    interface ParentComponent {
        fun createUserComponent(): NotInUserModuleUserComponent
    }
}
```

But this gives me grief that `error: [Dagger/MissingBinding] sk.o2.mojeo2.auth.NotInUserModuleUserComponent cannot be provided without an @Provides-annotated method.`

This is should not work, hence why you hinted at `@MergeSubcomponent.Factory`?  Or should it?

**Comment by vRallev** [comment]
That should work and it works for us (also in the integration tests). Make sure that `NotInUserModuleUserComponent` is annotated with `@MergeSubcomponent`.

**Comment by ursusursus** [comment]
Yea but is not, that was the point. So if I want to create the component in a another module, I should do that via regular gradle dependency management and include the module that contains the factory method?

**Comment by vRallev** [comment]
Dagger will generate all code for subcomponents where the main component is defined. So yes, you need to link them.

**Comment by ursusursus** [comment]
I see. Btw why do you use factory methods? Those seem to be discouraged by dagger team and painful when args need to be passed in

**Comment by vRallev** [comment]
We almost never pass in args. It works well for us also for other reasons.

**Comment by ursusursus** [comment]
Alright but aren't they all functionally equivalent btw? (@Factory, @Builder, factory method) and thefore just a matter of taste?

**Comment by vRallev** [comment]
Yes, I believe so.
