### ISSUE TITLE
Expose `CodeGenerator` interface

### ISSUE THREAD

**Issue by vRallev** [square/anvil#265]
This would allow consumers to create there own `CodeGenerator` and generate code at compile time. We have several uses cases for that internally like contributing `ScreenRobot`. But also external users would like this feature (some had to fork Anvil for that).

This would require breaking up the `:compiler` module in an API module. `CodeGenerators` would need to be loaded through a service loader probably. 

Tasks for WIP:
- [x] `GeneratedFile` should not be an inner class.
- [x] Create an `anvil` configuration to add dependencies to the Kotlin compiler plugin classpath.
- [x] Eliminate `CodeGenerator.flush()`.
- [x] Update the README.
- [x] How should errors be propagated? Should `AnvilCompilationException` be exposed?

**Comment by RBusarow** [comment]
This is fantastic! I've been meaning to make a feature request for exactly this.  I'd be happy to take a stab at the implementation over the weekend, if you're open to it.

**Comment by ZacSweers** [comment]
I've been chatting with Ralf about a possible design for it as we have a pretty good use case in mind, let me take a spin on it first

**Comment by RBusarow** [comment]
Sounds great. 😃

**Comment by ZacSweers** [comment]
PR is up! https://github.com/square/anvil/pull/267
