### ISSUE TITLE
[Question/Improvement] replace Module without creating TestComponent

### ISSUE THREAD

**Issue by chrisjenx** [square/anvil#272]
I have a small feature module, we generate a graph with two components:
`AppScope` and `FeatureScope`

We have something pretty standard, a singleton scope and subcomponents which we use Anvil to contribute the builders and modules:

// main/AppBindings
```
@Singleton
@MergeComponent(AppScope::class)
interface AppComponent {
}
```

// main/FeatureBindings
```
@SingleIn(FeatureScope::class)
@MergeSubcomponent(FeatureScope::class)
interface FeatureComponent {
  fun inject(activity: FeatureActivity)
  @Subcomponent.Factory
  interface Builder {
    fun create(): FeatureComponent
  }
  @ContributesTo(AppScope::class)
  interface Parent {
    fun featureComponent(): FeatureComponent.Factory
  }
}

@Module
@ContributesTo(FeatureScope::class)
interface FeatureBinding {
  @Binds fun FeatureApiImpl.bindFeatureApi(): FeatureApi
}

```

This all works as intended :+1: 

Where I guess I get confused is that we want to override `FeatureBinding` in AndroidTest, I was under the assumption that you could do something as simple as:

// androidTest/FeatureBindings
```
@Module
@ContributesTo(FeatureScope::class, replaces = [FeatureBinding::class])
class TestFeatureModule {
  @Provides fun provideFeatureApi(): FeatureApi = mock()
}
```

After looking, I under stand why this doens't work, Anvil is working as intended, but isn't actually running again because it allready generated that component in the `main/srcSet`.

I guess I'm asking, is there any way/interest/improvement to be made here to nudge dagger to regenerate the component in this case? Or is creating the `TestFeatureComponent` the only way right now due to Daggers limitations?

**Comment by vRallev** [comment]
#160 only talks about modules, but it actually means compilation units. It will also support what you're asking for. Therefore, I'm closing this ticket as a duplicate.

**Comment by chrisjenx** [comment]
Ahh sorry, I did look at that first and didn't realize it would cover this use case. Sounds good thank you!
