### ISSUE TITLE
Remove KotlinGradleSubplugin with Kotlin 1.4

### ISSUE THREAD

**Issue by vRallev** [square/anvil#30]
The class `KotlinGradleSubplugin` is deprecated in favor of `KotlinCompilerPluginSupportPlugin`. When Kotlin 1.4 is out this project is migrated, then `HephaestusSubplugin` should be removed and the new API be used instead.

**Comment by stephanenicolas** [comment]
For reference: https://youtrack.jetbrains.com/issue/KT-40214
