### ISSUE TITLE
Publish annotations as a multiplatform artifact

### ISSUE THREAD

**Issue by abyrnes** [square/anvil#309]
It would be nice if the `annotation` module were published as a multiplatform artifact so Anvil annotations could be used in common* source sets.

It may seem like an odd request since dagger is specific to the jvm, but with some simple `expect`/`actual` declarations, the annotations can easily be used in common source.

This can be done with Anvil annotations as well, but there's currently an issue where default parameters don't work on the `expect` declaration. So having to specify all 5 parameters for something like `ContributesBinding` can become quite annoying when I usually only want to specify the `scope`, for example.

**Comment by vRallev** [comment]
I'd find this misleading, but at the same time I have little experience with Kotlin multiplatform. I'd suggest to do this the other way around: Create common annotations in your code base and use as `expect` the Anvil annotations on the JVM side. Would that work? 

I don't want to give the impression that Anvil supports Kotlin multiplatform.

**Comment by abyrnes** [comment]
That does actually work. Initially I thought it didn't because the IDE was giving me errors regarding having default values on the `expect` declaration. There seems to be a whole other slew of issues though, and I understand not wanting to give the impression that anvil supports KMP.

Might just have to wait until ksp is multiplatform and dagger supports ksp
