### ISSUE TITLE
PsiUtils' requireClassDescriptor fails to resolve generated types

### ISSUE THREAD

**Issue by RBusarow** [square/anvil#310]
Given this generated class:

``` Kotlin
@ContributesBinding(AppScope::class)
class GeneratedFooImpl @Inject constructor() : Foo
```

Both versions of `requireClassDescriptor` will fail to resolve `GeneratedFooImpl`.  This happens with any of the contributes/merge generators.

The new `RealAnvilModuleDescriptor` is being used, but it doesn't do any good since we're trying to get the `ClassDescriptor` instead of just an `FqName`.

Some `requireClassDescriptor` calls can be replaced with existing Psi calls, like when getting the scope argument in `BindingGenerator`.  `KtClassOrObject.checkClassExtendsBoundType` seems much more awkward, though, since that's trying to resolve super types.

**Comment by vRallev** [comment]
This one is challenging. Replacing all `requireClassDescriptor` calls in `BindingModuleGenerator` isn't possible, likely. I can make the situation better for `ContributesBindingGenerator` though. As a workaround I suggest you generate a Dagger module with a binding method.

**Comment by RBusarow** [comment]
Thanks for your updates and the suggestion.  I have to admit, I kind of forgot that normal Dagger modules exist!

I'm able to do nearly everything I need now, leaning on a vanilla Dagger module.  I do have some more changes to `BindingModuleGenerator` and how we get the scope and exclude FqName.  I'll try to get the PR out this afternoon.
