### ISSUE TITLE
2 files found with path 'kotlin/internal/internal.kotlin_builtins' from inputs, using Anvil compiler-api module

### ISSUE THREAD

**Issue by himdeve** [square/anvil#347]
Can u please help how to properly exclude these files in packagingOptions? Even better would be to fix this problem in the lib. Thank u very much!

I am trying to use this api:
api "com.squareup.anvil:compiler-api:${latest_version}"

When I build my app, I get the following error:

> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'kotlin/internal/internal.kotlin_builtins' from inputs:
      - C:\Users\himdeve\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-compiler-embeddable\1.5.10\9c35134a025cab7a1e6eee0d87d241c2f30c1218\kotlin-compiler-embeddable-1.5.10.jar
      - C:\Users\himdeve\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.5.10\da6a904b132f0402fa4d79169a3c1770598d4702\kotlin-stdlib-1.5.10.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
     
     
And there is also a problem while using the "com.squareup.anvil:compiler-api" dependency, it requires Android 8 (minSdk 26). It is because compiler-api has depenencies on kotlin compiler:

```
dependencies {
  api project(':annotations')
  api deps.kotlin.compiler
}
```
 
And the error above is also because of the kotlin compiler.

I am using windows 10, kotlin version 1.5.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8), anvil: com.squareup.anvil:gradle-plugin:2.2.1 (didnt help upgrade to the latest version), agp: com.android.tools.build:gradle:4.2.1

**Comment by vRallev** [comment]
The error message already tells you what to do: 
> Adding a packagingOptions block may help, please refer to
https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
for more information

This is an issue independent of Anvil. 

The other issue
> it requires Android 8 (minSdk 26)
This is not true. This artifact is a JVM module (.jar) and not an Android module (.aar). Your project seems to be misconfigured. It's better to ask such questions on Stackoverflow.
