### ISSUE TITLE
TestAppComponent seems to pickup unrelated subscopes as well, making integration tests impossible

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#350]
Hi, 
Here is a repro of what I'm seeing https://github.com/ursusursus/AnvilRepro2

The goal is still to create a android-less app component, so I create fake modules which replace the android ones as suggested
I think the setup is correct
https://github.com/ursusursus/AnvilRepro2/blob/master/app/src/test/java/sk/foo/myapplication/DaggerTest.kt

If I run this, I see
```
C:\Users\ursus\AndroidStudioProjects\MyApplication11\app\build\tmp\kapt3\stubs\debugUnitTest\sk\foo\myapplication\TestAppComponent.java:9: error: [Dagger/MissingBinding] android.content.Context cannot be provided without an @Provides-annotated method.
public abstract interface TestAppComponent extends sk.foo.myapplication.SubScopedComponent.ParentComponent {
                ^
      android.content.Context is injected at
          sk.foo.myapplication.AndroidSubScopedModule.somethingSubScoped(context)
      sk.foo.myapplication.SomethingSubScoped is requested at
          sk.foo.myapplication.PartialSubScopedComponent.getDependency() [sk.foo.myapplication.TestAppComponent ? sk.foo.myapplication.SubScopedComponent]
```
Which makes no sense to me. I'm only trying to setup @AppScope component, why are @SubScope things complaining about missing Context?

And, for some reason it seems to be tied to when a component exposes a getter
https://github.com/ursusursus/AnvilRepro2/blob/master/app/src/main/java/sk/foo/myapplication/SubScopedComponent.kt#L31

If you comment out the getter, it compiles and runs.

(TLDR; @SubScope component is subcomponent of @AppScope component, and when only setting up test @AppScope component, @SubScope bindings complain, when though they're not related (I think))

I get that anvil scans whole of class path and @SubScope is there and therefore attached the factory to the TestAppComponent as well, but ..I'd still expect that to be somewhat lazy, I don' want to deal with all subscopes in this test at all

Let me know if I can be of any help

**Comment by vRallev** [comment]
This is a better question for Stackoverflow, because this is NOT an Anvil bug. I looked at it and your configuration is wrong. The problem is your subcomponent:
```kotlin
@SubScope
@MergeSubcomponent(SubScope::class)
interface SubScopedComponent {

    @ContributesTo(AppScope::class)
    interface ParentComponent {
        val subScopedComponentFactory: Factory
    }

    @Subcomponent.Factory
    interface Factory {
        fun create(): SubScopedComponent
    }
}
```
Notice that you contribute `ParentComponent` to the `AppScope`. In your tests your `AppScope` component also picks up this interface and merges it. So your subcomponent and the test app component ARE related. 

I was able to fix your test like this:
```kotlin
@AppScope
@MergeComponent(AppScope::class, exclude = [SubScopedComponent.ParentComponent::class])
interface TestAppComponent
```

**Comment by ursusursus** [comment]
So just to clarify, I see why `SubScopedComponent.ParentComponent` gets merged into TestAppComponent. But the real reason of the error is that it provides Factory of the SubScopedComponent, right?

Is the exclusion idiomatic for tests, or is there something better?

**Comment by vRallev** [comment]
> But the real reason of the error is that it provides Factory of the SubScopedComponent, right?

Right

Exclusions aren't idiomatic, but necessary for tests sometimes. More often in our codebase we see fake Dagger modules / bindings replace real implementations in tests with the `replaces` attribute.

**Comment by ursusursus** [comment]
Hmm well that what I was trying to do, isolate a binding which needs Context into its own module and then replace it with a module which provides a fake

Is there  a way I could do this for the subcomponent factory?

**Comment by vRallev** [comment]
You can alway contribute another interface for the subcomponent and replace the other one. But I think the exclude works best in your case.

**Comment by ursusursus** [comment]
I chose to have my test factory replace the real one, thanks!
