### ISSUE TITLE
ContributesTo partial component not picked up when its not a dependency of a module that declares MergeSubcomponent

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#357]
Hi, I ran into this issue, based on our previous conversation, as to declare MergeSubcomponent in a :submodule, with generateDaggerFactories (and that only MergeComponent needs to be in :app module with kapt enabled)

It compiles, and mostly works, i.e. @Modules with @ContributesTo do get picked up no problem, but the partial @ControbutesTo component does not; and fails at runtime with a class cast exception

- If I put lib2 as a dependency of lib1, then it works; but that clashes with my design of the actual project, where I have everything split into contract+impl modules; and usualy have the partial components in the impl module, and impl module should not be a dependency of anything but :app module

Does this work as expected (and I have to switch around my design) or is a bug?

Repro https://github.com/ursusursus/AnvilRepro2

**Comment by ursusursus** [comment]
and also I noticed if I declare

```
@ContributesTo(LibraryScope::class)
interface BarLibaryComponent {
    val somethingLibrary2: SomethingLibrary2
}
```
in :app (so upstream from :lib), then it doesn't work as well (class cast exc at runtime)

**Comment by RBusarow** [comment]
Anvil won't generate Subcomponents.  They're effectively the same as Components.  All Anvil does is merge all the contributed interfaces and modules, then add the Dagger annotation.  That's mentioned in the README:

>@MergeComponent is used instead of the Dagger annotation @Component. Anvil will generate the Dagger annotation and automatically include all modules and component interfaces that were contributed the same scope.
@MergeSubcomponent is similar to @MergeComponent and should be used for subcomponents instead.

In order to generate a Component or Subcomponent, you need to apply Kapt and Dagger's annotation processor.

**Comment by vRallev** [comment]
I'm closing this issue, because there's no problem in the library. Questions about project configurations or misunderstandings belong to Stackoverflow or other forums and not an issue tracker.

**Comment by ursusursus** [comment]
> Kapt for Dagger only needs to be enabled for @MergeComponent, but not @MergeSubcomponent. Therefore, you only need to enable Kapt in your app module. That means you can put your UserComponent into a library module and don't need enable Kapt

https://github.com/square/anvil/issues/263#issuecomment-833910698

Can I ask what does this then refer to?

**Comment by ursusursus** [comment]
ok as you wish https://stackoverflow.com/questions/68734684/contributesto-partial-component-not-picked-up-when-its-not-a-dependency-of-a-mod

follow up there if you can, please
