### ISSUE TITLE
Custom CodeGenerator debugging

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#364]
Hi, i'm trying to use the new custom code generator api. I might be stupid but
1) how do you debug the CodeGenerator, or atleast how do you print something to console? Both are ignored for me, so I've no idea what im doing. Java annotation processors used to have some sort of Enviroment thing to be used for such thing, here I don't see nothing similar.
2) where is the `anvil project(":my-custom-compiler")` is supposed to be in a multi-module project? In every module where there is the custom annotation which my compiler looks for? Or just in top level :app module?

Thanks

**Comment by vRallev** [comment]
This is not a forum for questions especially since you asked me directly in the Kotlin Slack. Use channels in this Slack or Stackoverflow to ask questions. This is an issue tracker.

**Comment by Programistich** [comment]
@vRallev can u sent your Slack contact?
