### ISSUE TITLE
2.3.4 factory generation with multibindings

### ISSUE THREAD

**Issue by Dkhusainov** [square/anvil#371]
After upgrading to latest(`2.3.4`) Anvil my compilation started to fail with incorrect imports:
`Type mismatch: inferred type is java.util.Set<MyType> but kotlin.collections.Set<MyType> was expected`

`2.3.4` imports `java.util.Set ` 
`2.3.3` imports `kotlin.collections.Set`

**Comment by Dkhusainov** [comment]
In the broken file replacing `import java.util.*` with explicit imports fixes the issue

**Comment by vRallev** [comment]
Can you please add a sample to reproduce the issue?

**Comment by Dkhusainov** [comment]
```
import java.util.*
import javax.inject.Inject

class bla @Inject constructor(
  val setMultibinding: Set<String>,
) {

  private val cache = TreeSet<String>()
}
```

**Comment by vRallev** [comment]
Thanks, I've uploaded a fix for the next release.
