### ISSUE TITLE
[Question] How i can create Singleton binding with Anvil?

### ISSUE THREAD

**Issue by LionZXY** [square/anvil#376]
Hi! I try to use Anvil in my multi-module project, but i have some problems with scope.

I'm trying to create a `Singleton` service, but it doesn't work, it gets created every time.

What i do:
```kotlin
abstract class AppGraph private constructor()

@Singleton
@MergeComponent(AppGraph::class)
interface AppComponent
```

And my service:
```kotlin
interface TestService

@ContributesBinding(AppGraph::class)
class TestServiceImpl @Inject constructor(): TestService
```

*Expected state*
DI create `TestServiceImpl` once and then reusable it

*Actual state*
DI create `TestServiceImpl` each times

You can try open https://github.com/flipperdevices/Flipper-Android-App/tree/feature/tos (branch `feature/tos`) and see `PairScreenStateDispatcherImpl_Factory` in `components/pair/impl` module

**Comment by RBusarow** [comment]
You have no `@Singleton` annotation on `TestServiceImpl`, so the binding isn't scoped.

```kotlin
interface TestService

@Singleton <------------- add this
@ContributesBinding(AppGraph::class)
class TestServiceImpl @Inject constructor(): TestService
```

**Comment by LionZXY** [comment]
After add `Singleton` annotation this service still create each time
https://github.com/flipperdevices/Flipper-Android-App/commit/b0eb1e484c1a432a74ffedfbd574d739f65d55ad

**Comment by LionZXY** [comment]
Soo... I found reason why it happens. 
I create small sample with this problem: https://github.com/LionZXY/anvil-singleton-example

After adding parameters to the constructor, the object is no longer a Singleton, although it was before. It's definitely not what I expect. Is there any description of why this was implement, if it's not a bug?

**Comment by vRallev** [comment]
Anvil doesn't change scopes, add or remove them. Since this isn't an Anvil issue, I'll close the ticket. I suggest to ask this question on Stackoverflow or Dagger maintainers itself.
