### ISSUE TITLE
Generating Component.Builder methods

### ISSUE THREAD

**Issue by mattinger** [square/anvil#389]
Im trying to use anvil with daggermock as a testing framework.  However, the issue i'm running into is that daggermock doesn't really like Component.Factory, which is understandable. So i would then use a Component.Builder.  However, because the list of modules is not known to me when writing the code, I can only create a builder which will internally create all the required modules:

```
@Component.Builder
interface Builder {
  @BindsInstance fun context(context: Context): Builder
   fun build(): MyComponent
}
```

Due to this, daggermock can't override the modules because you can't create an instance and pass it to the builder (which is my understanding of how daggermock works).

What i'd love is to be able to generate a builder in anvil from something like this:

```
@MergeComponent.Builder
interface MergeBuilder {
   @BindsInstance fun context(context: Context): Builder
   fun build(): MyComponent
}
```

And have anvil recognize that, and create a full fledged builder with setters for all the collected modules.

**Comment by vRallev** [comment]
I haven't heard of daggermock before. I don't see us implementing what you're asking for. However, Anvil provides extension points to create your own custom code generator and I think what you're asking for could be solved this way. Please take a look at the [documentation](https://github.com/square/anvil/tree/main/compiler-api).

**Comment by vRallev** [comment]
You're supposed to replace bindings from the `main` source set in the `androidTest` source set. Not the other way around.

**Comment by vRallev** [comment]
Closing this for now.
