### ISSUE TITLE
Should display error when plugin not applied

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#40]
Hi, since using this I shot my self in the foot bunch of times on this issue

for whatever reason I can include @ContributesTo annotation, and it compiles, however at runtime looking up components via the given annotated componen type fails

And then I noticed I didnt `apply plugin: "com.squareup.anvil"` in the given module. I apply it. Then it works

Unless plugin is applied, @ContributesTo should not be visible. I'm including all my project dependencies via `implementation`, so it could not have leaked as a transitive dependency? I'm not sure how plugins are handled though, or however else does the annotation get on class path for the incriminated module

**Comment by vRallev** [comment]
Yes, I agree. The annotations are added as `api` dependency, because they're actually exposed (on the public type). But I see  how this can cause issues downstream like you described.

**Comment by ursusursus** [comment]
Added by who, if given module doesnt apply the plugin?

**Comment by vRallev** [comment]
You probably apply the plugin in one of the library modules that you import. The Gradle plugin adds this dependency.

**Comment by ursusursus** [comment]
Yea I add it in `:base`, and do I include `:base` in the given module. But I include it as `implementation project(":base")` -- doesn't that mean "Include base but none of its transitive dependencies?", i.e. not `api`, which would include transitive deps.

**Comment by vRallev** [comment]
No, that's not what `implementation` means, see https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation
