### ISSUE TITLE
Re: https://slack.engineering/extending-anvil-for-fun-and-profit/

### ISSUE THREAD

**Issue by JohnBuhanan** [square/anvil#417]
I reproduced how y'all used Anvil to do Activity injection in the following article:
https://slack.engineering/extending-anvil-for-fun-and-profit/

And I wanted to give a heads up that Jake Wharton's `dagger-reflect` can't use MembersInjectors for its latest release of 0.3.0

The commit to fix it exists on the `main/master` branch, but it has not been released yet, and may never be since the fix was committed about a year ago.

Any chance there is a solution that does not use MembersInjectors so I can stay compatible with `dagger-reflect 0.3.0`?

**Comment by vRallev** [comment]
I'm not sure I understand the question. Whether you use member injection is totally up to you, your code and how you inject dependencies with Dagger and Anvil.

**Comment by JohnBuhanan** [comment]
My apologies.

I meant in the article you guys accomplish Activity injection by making heavy use of MembersInjector.

I was just wondering if there was a way to accomplish it without using MembersInjector.

**Comment by vRallev** [comment]
I guess you could expose all dependencies in the component through functions:
```kotlin
@MergeComponent(..)
interface YourComponent {
  fun dep1(): Dep1
  fun dep2(): Dep2
}
```
Since this is an issue tracker I suggest asking such questions at Stackoverflow. I'll close the ticket therefore.
