### ISSUE TITLE
Remove support for the old compiler backend

### ISSUE THREAD

**Issue by vRallev** [square/anvil#422]
Kotlin 1.6 will deprecate the old compiler backend. The IR compiler backend for JVM/Android projects became the default with Kotlin 1.5. At this point there should be no reason why someone on those platforms still uses the old backend.

Anvil still supports both. But supporting the old backend will become a blocker for #236. Repeated annotations with a runtime / compile time retention are only implemented in the IR backend and not in the old backend. Anvil will remove support for the old backend to support repeated annotations.

My plan is to bump Kotlin 1.6 for Anvil and release a final version supporting both backends. This will unblock anyone still using the old backend and Kotlin 1.6. There is a binary incompatible change within the Kotlin compiler that makes Anvil versions compiled with 1.5 incompatible with 1.6. This last release built with 1.6 for both backends is therefore necessary.

After that support for the old backend will be removed. Newer Anvil versions will only support the IR backend.

**Comment by vRallev** [comment]
I just learnt that the stub generating task is always using the old backend:
![image](https://user-images.githubusercontent.com/1558045/141246338-c4f6c16e-7363-402a-a947-714552b02ce0.png)

We probably won't be able to remove any code. But this doesn't seem to be a big problem. We only need to make sure that Anvil itself is compiled with the IR backend. Consumers can still use both.

For #236 this means if you use the old backend, then you can only apply the repeatable annotations once. The Kotlin compiler will fail otherwise:
>  Repeatable annotations with non-SOURCE retention are only supported starting from Kotlin 1.6

The old backend assumes language level 1.5. This restriction doesn't seem to exist for the stub generating task. 

If you use the IR backend, then you can use the repeatable annotations as you'd expect.

**Comment by vRallev** [comment]
Update: there will be [a solution](https://youtrack.jetbrains.com/issue/KT-49682) in Kotlin 1.7.

**Comment by SteinerOk** [comment]
@vRallev I apologize for the off-topic question, but I think it's better than creating a separate topic because of a trifle.
Anvil is compatible with Kotlin 1.6.10, can I update my project to this version?

**Comment by vRallev** [comment]
@SteinerOk Please see the release notes: https://github.com/square/anvil/releases Use version `2.3.10-1-6-0`, it's also compatible with Kotlin 1.6.10.

**Comment by vRallev** [comment]
This can be tested [with Kotlin 1.7.20](https://youtrack.jetbrains.com/issue/KT-49682/Support-JVM-IR-in-KAPT-stub-generation). The IR backend for Kapt will [become the default](https://youtrack.jetbrains.com/issue/KT-53135) with Kotlin 1.8.0.

**Comment by vRallev** [comment]
Testing it in #630. There still seems to be an issue with the compile-testing library.

**Comment by vRallev** [comment]
Target is Kotlin 1.8.20.
