### ISSUE TITLE
How to inject entry points (activities, fragments) when the host app contains the component.

### ISSUE THREAD

**Issue by mattinger** [square/anvil#424]
So here's my use case I'm not quite sure how to use anvil for:

* Modules are declared in libraries, along with activities and fragments
* Host application contains the class annotated with the @MergeComponent annotation. 

My question is how would you go about injecting the activities and fragments in this case?  The library would only have access to the Scope class itself, and not the actual component, so i'm not sure how it would get a hold of it.  I'm basically looking for the anvil equivalent of the @AndroidEntryPoint in hilt.

**Comment by mattinger** [comment]
Even with an @MergeSubcomponent, i'm not sure how one would get an instance of the subcomponent to do the injection, since you'd have to have the parent component available in order to get the subcomponent.  And the parent component would end up living in the host app, and wouldn't be available to the library.

**Comment by RBusarow** [comment]
### option 1 - create interfaces and use `@ContributesTo` to merge them into the component

```kotlin
// MyActivity.kt in a library
@ContributesTo(AppScope::class)
interface MyActivityComponent {
  val someDependency: SomeDependency

  // or just an inject function
  fun inject(myActivity: MyActivity)
}

class MyActivity: Activity() {
  val dependency = Components.get<MyActivityComponent>().someDependency
}
```

wherever you define your scope:
```kotlin
abstract class AppScope private constructor()

/** Singleton holder for your application-level Component */
object Components {

  @PublishedApi
  @Suppress("ObjectPropertyNaming")
  internal val _components = mutableSetOf<Any>()

  fun add(component: Any) {
    _components.add(component)
  }

  inline fun <reified T> get(): T = _components
    .filterIsInstance<T>()
    .single()
}
```

And the application:
```kotlin
class MyApplication: Application() {

  override fun create() {

    val component = DaggerMyAppComponent.factory()
      .create(/* ... */)

    Components.add(component)
  }
}   
```

### option 2 - write your own AndroidInjector

Anvil's code generation APIs are public, and it's possible to write your own `CodeGenerator` implementation which will be executed by Anvil.  @ZacSweers wrote an article about your exact use-case [here](https://slack.engineering/extending-anvil-for-fun-and-profit/).

### option 3 - Tangle

https://github.com/RBusarow/Tangle

I wrote Tangle with the intent of offering Anvil equivalents to the Hilt API's.  Its [member injection](https://rbusarow.github.io/Tangle/docs/member-injection/) functionality is roughly equivalent to Hilt's.

**Comment by vRallev** [comment]
I'll close this issue due to inactivity (and it being more of a question rather than an issue). Feel free to respond nonetheless.

**Comment by JohnBuhanan** [comment]
@RBusarow Can Option 1 be adapted to work with a BaseActivity class?

P.S.- Option2 and Option3 don't seem to work with dagger-reflect

**Comment by RBusarow** [comment]
Option #1 will kind of work, if you define the properties in the interface instead of writing the `inject(...)` functions.

But again, the solution to your problem seems to be just giving up on dagger-reflect and using Anvil's factory generation instead.
