### ISSUE TITLE
[Generated Factories] Another MembersInjectors for super classes issue?

### ISSUE THREAD

**Issue by JohnBuhanan** [square/anvil#438]
This looks an awful lot like https://github.com/square/anvil/issues/343

I confirmed this issue still exists when I update to latest Dagger and Anvil.  (2.40.5 and 2.3.10)
```
GradleProject1
--------------
class A : B <-- Well-formed MembersInjector
class B : C <-- broken

GradleProject2
--------------  
class C <-- Well-formed MembersInjector
```

When I inserted an intermediary class into the chain it made it clear that it breaks at the boundary between gradle projects.
```
GradleProject1
--------------
class A : B <-- Well-formed MembersInjector
class B : C <-- broken

GradleProject2
--------------  
class C : D <-- Well-formed MembersInjector
class D <-- Well-formed MembersInjector
```
```
GradleProject1
--------------
class A : B <-- Well-formed MembersInjector
class B : C <-- Well-formed MembersInjector
class C : D <-- broken

GradleProject2
--------------  
class D <-- Well-formed MembersInjector
```

Do I need to make a sample project, or is this good enough?

**Comment by RBusarow** [comment]
It's pretty light on details, but I was able to find an issue which doesn't quite match your description.

Given something like this:
``` kotlin
// :lib1

abstract class Base {
  @Inject lateinit var dep1: Dep1
}
```

```kotlin
// :lib2

abstract class Mid : Base() {
  @Inject lateinit var dep2: Dep2
}

class Impl : Mid() {
  @Inject lateinit var dep3: Dep3
}
```

The `MembersInjector` for `Impl` is this:
```kotlin
public class Impl_MembersInjector(
  private val dep1: Provider<Dep1>,
  private val dep2: Provider<Dep2>,
  private val dep3: Provider<Dep3>
) : MembersInjector<Impl> {
  public override fun injectMembers(instance: Impl): Unit {
    Mid_MembersInjector.injectDep1(instance, dep1.get())        // this line is the error
    lib2.Mid_MembersInjector.injectDep2(instance, dep2.get())
    Impl_MembersInjector.injectDep3(instance, dep3.get())
  }

  public companion object {
    @JvmStatic
    public fun create(
      dep1: Provider<Dep1>,
      dep2: Provider<Dep2>,
      dep3: Provider<Dep3>
    ): Impl_MembersInjector = Impl_MembersInjector(dep1, dep2, dep3)

    @JvmStatic
    @InjectedFieldSignature("lib2.Impl.dep3")
    public fun injectDep3(instance: Impl, dep3: Dep3): Unit {
      instance.dep3 = dep3
    }
  }
}
```
The `MembersInjector` is trying to invoke the correct "inject___" function for the base class, but from the wrong injector class.  It may just be an off-by-one error.

I can look into this more later tonight.

**Comment by JohnBuhanan** [comment]
> It's pretty light on details, but I was able to find an issue which doesn't quite match your description.
> 
> Given something like this:
> 
> ```kotlin
> // :lib1
> 
> abstract class Base {
>   @Inject lateinit var dep1: Dep1
> }
> ```
> 
> ```kotlin
> // :lib2
> 
> abstract class Mid : Base() {
>   @Inject lateinit var dep2: Dep2
> }
> 
> class Impl : Mid() {
>   @Inject lateinit var dep3: Dep3
> }
> ```
> 
> The `MembersInjector` for `Impl` is this:
> 
> ```kotlin
> public class Impl_MembersInjector(
>   private val dep1: Provider<Dep1>,
>   private val dep2: Provider<Dep2>,
>   private val dep3: Provider<Dep3>
> ) : MembersInjector<Impl> {
>   public override fun injectMembers(instance: Impl): Unit {
>     Mid_MembersInjector.injectDep1(instance, dep1.get())        // this line is the error
>     lib2.Mid_MembersInjector.injectDep2(instance, dep2.get())
>     Impl_MembersInjector.injectDep3(instance, dep3.get())
>   }
> 
>   public companion object {
>     @JvmStatic
>     public fun create(
>       dep1: Provider<Dep1>,
>       dep2: Provider<Dep2>,
>       dep3: Provider<Dep3>
>     ): Impl_MembersInjector = Impl_MembersInjector(dep1, dep2, dep3)
> 
>     @JvmStatic
>     @InjectedFieldSignature("lib2.Impl.dep3")
>     public fun injectDep3(instance: Impl, dep3: Dep3): Unit {
>       instance.dep3 = dep3
>     }
>   }
> }
> ```
> 
> The `MembersInjector` is trying to invoke the correct "inject___" function for the base class, but from the wrong injector class. It may just be an off-by-one error.
> 
> I can look into this more later tonight.

You're the man @RBusarow :P (Love your work with Tangle btw)

In case it helps I made a sample Repo: https://github.com/JohnBuhanan/anvil-factory-generation-members-injector-issue

**Comment by gmarques33** [comment]
I just ran into a pretty similar issue, but as I was using constructor injection it was a `Factory` instead of a `MembersInjector`.

In my case I have:

// :lib1
```kotlin
abstract class Base {
  @Inject lateinit var dep1: Dep1
}
```

// :lib2
```kotlin 
class Impl @Inject constructor(private val dep2: Dep2) : Base() {
}
```

On my DaggerApplicationComponent it will correctly generate:
```java
this.ImplProvider = Impl_Factory.create(dep1Provider, dep2Provider);
```

But the `Impl_Factory` generated by Anvil will only have a `create(dep2: Provider<Dep2>)` method:
```kotlin
import com.myproject.Dep2
import dagger.`internal`.Factory
import javax.inject.Provider
import kotlin.Suppress
import kotlin.jvm.JvmStatic

public class Impl_Factory(
  private val dep2: Provider<Dep2>
) : Factory<Impl> {
  public override fun `get`(): Impl = newInstance(dep2.get())

  public companion object {
    @JvmStatic
    public fun create(dep2: Provider<Dep2>):
        Impl_Factory = Impl_Factory(dep2)

    @JvmStatic
    public fun newInstance(dep2: Dep2): Impl =
        Impl(dep2)
  }
}
```

If I use kapt, Dagger will generate:
```Java
// Generated by Dagger (https://dagger.dev).
import com.myproject.Base_MembersInjector;
import com.myproject.Dep1;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class Impl_Factory implements Factory<Impl> {
  private final Provider<Dep2> dep2Provider;

  private final Provider<Dep1> dep1Provider;

  public Impl_Factory(Provider<Dep2> dep2Provider,
      Provider<Dep1> dep1Provider) {
    this.dep2Provider = dep2Provider;
    this.dep1Provider = dep1Provider;
  }

  @Override
  public Impl get() {
    Impl instance = newInstance(dep2Provider.get());
    Base_MembersInjector.injectDep1(instance, dep1Provider.get());
    return instance;
  }

  public static Impl_Factory create(
      Provider<Dep2> dep2,
      Provider<Dep1> dep1Provider) {
    return new Impl_Factory(dep2Provider, dep1Provider);
  }

  public static Impl newInstance(Dep2 dep2) {
    return new Impl(dep2);
  }
}
```

**Comment by RBusarow** [comment]
> I just ran into a pretty similar issue, but as I was using constructor injection it was a `Factory` instead of a `MembersInjector`.
> ....

@gmarques33 this is indeed similar, but it's a slightly different issue.  There was one bug regarding "grand-super" classes in a different module, and another regarding direct super classes.  I created a new issue for it: #439.

Fixes for both will be up shortly

**Comment by JohnBuhanan** [comment]
I'm excited to try this!

What is easiest way to test this?

I'm trying to build anvil locally and having headaches.

**Comment by vRallev** [comment]
Done: `2.3.11-SNAPSHOT` Note that this snapshot will only work for Kotlin 1.5 and not 1.6.

**Comment by JohnBuhanan** [comment]
Sweet. Much thanks :)
