### ISSUE TITLE
Defining MergeComponent in a library

### ISSUE THREAD

**Issue by mattinger** [square/anvil#441]
I was hoping to have a standard component architecture, and define 3 scopes in a library:
* ApplicationScope
* ActivityScope
* FragmentScope

I would then make 3 components, one using @MergeComponent and two using @MergeSubcomponent along with the appropriate factory interfaces and methods in the parents:

```
@Singleton
@MergeComponent(ApplicationScope::class)
interface ApplicationComponent {
    fun activityComponent(): ActivityComponent.Factory

    @Component.Factory
    interface Factory {
        fun create(@BindsInstance application: Application): ApplicationComponent
    }
}
```

I would then compile this without the anvil compiler and publish as an .aar.

I then want to have the host application use the anvil compiler, and take advantage of these components, along with all the other @ContributesTo, etc.... annotations.

However, it seems that the anvil compiler does not actually process the @MergeComponent annotation if the class in question is outside of the module which is currently being compiled.

Any suggestions on what i'm doing wrong, or how to address this?  I'm trying basically to replicate the idea of what hilt does with it's 3 standard components, but using anvil instead.

**Comment by vRallev** [comment]
This is working exactly like expected. How should Anvil process classes outside of the compilation unit? You import dependencies in a binary already compiled and it would kill the performance if you recompile dependencies over and over again. 

What you're looking for sounds a little bit like `[@ContributesSubcomponent](https://github.com/square/anvil/blob/main/annotations/src/main/java/com/squareup/anvil/annotations/ContributesSubcomponent.kt)` instead of `@MergeSubcomponent`. That might work for you. Note that there's no such annotation for the root component.

**Comment by digitalbuddha** [comment]
Here's an example I had working, it defines components App/User/Activity within a base module. Next, it creates one component definition in App module and then gets each subcomponent from the parent.
https://gist.github.com/digitalbuddha/d1b1899032c7cc0266eade5b153a9c4a

**Comment by mattinger** [comment]
THe root component isn't really my issue @vRallev .  I'm using a component registry to get the root component:

```
object Components {
    @PublishedApi
    @Suppress("ObjectPropertyNaming")
    internal val _components = mutableSetOf<Any>()

    fun add(component: Any) {
        _components.add(component)
    }

    inline fun <reified T> get(): T =
        _components
            .filterIsInstance<T>()
            .single()
}
```

I have the application create and save the component here, and then i can contribute interfaces to it for injection.  The issue comes when i want to create an activity level component, and have it saved with the activity.  I use a function that i borrowed form the internet named `scopedComponent` that stores the component inside a view model so i can associate it with a particular activity or fragment.  The issue is that i have to know how to create the component in case it doesn't exist, and the libraries might have issues with this.  I suppose i could create an activity and fragment subcomponent for each library.

Is that what you'd recommend?

**Comment by vRallev** [comment]
This is really up to you how you want to manage that. I don't have a recommendation.
