### ISSUE TITLE
Still MemberInjectors issue for super classes in different Gradle project

### ISSUE THREAD

**Issue by JohnBuhanan** [square/anvil#442]
@RBusarow 
I just tried latest SNAPSHOT, and we are closer!

I now see this when I try to build here:
https://github.com/JohnBuhanan/anvil-factory-generation-members-injector-issue

```
public class FeatureActivity1_MembersInjector(
  private val b1: Provider<B1>,
  private val b2: Provider<B2>,
  private val f1: Provider<F1>
) : MembersInjector<FeatureActivity1> {
  public override fun injectMembers(instance: FeatureActivity1): Unit {
    BaseActivity2_MembersInjector.injectB1(instance, b1.get())  <--- Should be BaseActivity1 I think?
    BaseActivity2_MembersInjector.injectB2(instance, b2.get())
    FeatureActivity1_MembersInjector.injectF1(instance, f1.get())
  }
...
```

**Comment by JohnBuhanan** [comment]
And this is probably the last change I need to benchmark my build with factory generation.

I'm trying to make a case to remove dagger-reflect.

**Comment by JohnBuhanan** [comment]
I'm stoked!  And could I humbly request one more snapshot publish after merge?

**Comment by vRallev** [comment]
@JohnBuhanan I published another [snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/squareup/anvil/compiler/2.3.11-SNAPSHOT/) with the fix. I only requested minor changes before I merge the PR.

**Comment by JohnBuhanan** [comment]
Beauty, I wish I could buy you guys a round of beers!  

I'll go try it out
