### ISSUE TITLE
Suppress/OptIn Lint warnings/errors are not ignored in Anvil/src-gen

### ISSUE THREAD

**Issue by chrisjenx** [square/anvil#488]
We have some `@OptIn` Errors/Warnings.  We add to certain classes to make sure Engineers are aware of the fallout from using certain classes, however the Kotlin Compiler will flag/fail on these classes when the anvil/src-gen is compiled.

Not sure the best approach, but I'm guessing either Anvil add's the Suppression/OptIn, or has a compiler flag set to ignore lint warnings? Looks like Dagger/KSP/KAPT might ignore these as they don't warn/fail on these lint checks.

(If theres already a plugin option appologies!)

**Comment by vRallev** [comment]
It would greatly help, if you could provide a tiny sample for that (maybe even create a unit test?). As a workaround you could also opt-into using the experimental APIs through compiler flags.

**Comment by chrisjenx** [comment]
Can do, will add an example.

Problem with adding to the compilerargs is it blanket covers the module.
Where we want explicit optin.

**Comment by chrisjenx** [comment]
So we have a `@InternalApi` defined:
```
@Retention(AnnotationRetention.BINARY)
@RequiresOptIn(
    message = ""
    level = RequiresOptIn.Level.ERROR
)
@MustBeDocumented
annotation class InternalOmegaApi
```

We are annotating internal classes with that optin.

```
@InternalOmegaApi
@Singleton class OmegaEngineImpl
@Inject constructor() : OmegaEngine
```

When the factory gets generated we get the compiler error:
```
public class OmegaEngineImpl_Factory(
) : Factory<OmegaEngineImpl> {

e: /Users/chrisjenkins/git/x-android/shared/shopper-omega/impl/build/anvil/src-gen-debug/com/x/shopper/omega/OmegaEngineImpl_Factory.kt: (38, 13): Error message
```

In normal use cases this would be fine, but as this is generated code, theres no way I can add: `@OptIn(InternalOmegaApi::class)` to the factory.

Not sure on the outcome, but a couple of potential fixes:
1. Disable lint warnings/errors on the generated src compile target (not sure if kotlin compiler is that granular) 
2. Add the equivilent opt-in for that class you are generating factories for (this is probably better but trying to track this seems allot as you would need to handle/suppress every lint warning/error)
3. Allow compiler flags to be passed through for Anvil (again not sure if kotlin plugins allows that level of granularity?)


Cheers!

**Comment by vRallev** [comment]
I've created a failing test: https://github.com/square/anvil/pull/502 I can't promise a solution anytime soon.

**Comment by vRallev** [comment]
I filed a feature request for Kotlin: https://youtrack.jetbrains.com/issue/KT-51249

**Comment by chrisjenx** [comment]
I guess what confuses me is how does Dagger/KAPT/KSP do this? As when dagger generates these factories Kotlin doens't blow up at compile time... are they doing the expensive operation hit as you said where they are adding supressions?

**Comment by vRallev** [comment]
Dagger generates Java. KSP is a separate compile task as well.

**Comment by RBusarow** [comment]
> I guess what confuses me is how does Dagger/KAPT/KSP do this? As when dagger generates these factories Kotlin doens't blow up at compile time... are they doing the expensive operation hit as you said where they are adding supressions?

The only KSP I've tested this against is Moshi, but it does not dynamically suppress anything.

Given this:
```kotlin
@RequiresOptIn
annotation class Scary

@Scary
@JsonClass(generateAdapter = true)
data class Thing(val name: String)
```
At compile-time, you'll get this:
> e: [...]/ThingJsonAdapter.kt: (22, 17): This declaration is experimental and its usage must be marked with '@com.squareup.Scary' or '@OptIn(com.squareup.Scary::class)'
e: [...]/ThingJsonAdapter.kt: (31, 23): This declaration overrides experimental member of supertype 'JsonAdapter' and must be annotated with '@com.squareup.Scary'
e: [...]/ThingJsonAdapter.kt: (31, 53): This declaration is experimental and its usage must be marked with '@com.squareup.Scary' or '@OptIn(com.squareup.Scary::class)'
e: [...]/ThingJsonAdapter.kt: (46, 12): This declaration is experimental and its usage must be marked with '@com.squareup.Scary' or '@OptIn(com.squareup.Scary::class)'
e: [...]/ThingJsonAdapter.kt: (51, 23): This declaration overrides experimental member of supertype 'JsonAdapter' and must be annotated with '@com.squareup.Scary'
e: [...]/ThingJsonAdapter.kt: (51, 58): This declaration is experimental and its usage must be marked with '@com.squareup.Scary' or '@OptIn(com.squareup.Scary::class)'
e: [...]/ThingJsonAdapter.kt: (52, 9): This declaration is experimental and its usage must be marked with '@com.squareup.Scary' or '@OptIn(com.squareup.Scary::class)'
e: [...]/ThingJsonAdapter.kt: (57, 34): This declaration is experimental and its usage must be marked with '@com.squareup.Scary' or '@OptIn(com.squareup.Scary::class)'

**Comment by vRallev** [comment]
PR is now green.
