### ISSUE TITLE
interface module contributions appear to get contributed to component merging rather than as modules

### ISSUE THREAD

**Issue by ZacSweers** [square/anvil#554]
We see a case where a simple interface module with a single binding like below

![image](https://user-images.githubusercontent.com/1361086/156258550-e6aa128a-dd72-42af-9ff2-8199b99e75f8.png)

Results in an error when this interface merged downstream rather than used as a module

```
/mnt/buildkite-agent/builds/mbr-buildkite-agent-android-iad-4iuo-1/slack/android-pull-request/apps/app-di/build/tmp/kapt3/stubs/internalDebug/slack/di/anvil/MainUserComponent.java:12: error: [slack.permissions.data.ChannelMutatorPermissionValidatorContributor.bind(slack.permissions.data.SlackPermissionValidator)] Members injection methods may only return the injected type or void.
public abstract interface MainUserComponent extends slack.app.di.UserComponent, slack.permissions.data.ChannelMutatorPermissionValidatorContributor, slack.createteam.ext.AuthedApiAccessor, 
```

**Comment by vRallev** [comment]
We have a test case for that: https://github.com/square/anvil/blob/main/compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt#L576-L599 

I tried many things now, but I cannot reproduce the bug no matter how I changed this test. Do you still see the issue? Is there anything important that I missed?

**Comment by vRallev** [comment]
Any update on this? Otherwise I'm inclined to close the ticket for now.

**Comment by ZacSweers** [comment]
I'll close it for now and revisit if I can track down a consistent repro. I haven't had time yet to revisit but I have seen other cases with interfaces that worked fine
