### ISSUE TITLE
Clarify code generation documentation

### ISSUE THREAD

**Issue by bubenheimer** [square/anvil#573]
I was attempting to utilize Anvil's custom code generation, but was not able to make the provided example work. It might help to put the wiki page into context in terms of Kotlin code generation experience needed; I assumed it was intended to be a somewhat streamlined approach that would not require prior code generation knowledge, or that I'd be able to figure things out just by digging through the given example and the APIs it references.

Just for reference, here is where I got stuck:
https://github.com/square/anvil/blob/1dfd6dc9ae0aed9a06b54ba6268f8b0968e6aacf/compiler-api/README.md?plain=1#L44

**Comment by SteinerOk** [comment]
I agree, code generation documentation is outdated since version 2.4.0-M1

**Comment by vRallev** [comment]
I agree, I've updated the guide. I also suggest taking a look at the many code generators within Anvil for more inspiration.

**Comment by bubenheimer** [comment]
You're providing an example with dependencies, but have a hidden agenda to leave out some deps that the example needs? Seems odd.

At least now it's clear that the intention is indeed to use `classAndInnerClassReferences()`, and the reader can piece together the rest. Thanks.
