### ISSUE TITLE
Generate bindings for top-level properties

### ISSUE THREAD

**Issue by bubenheimer** [square/anvil#578]
Annotated top-level properties such as below would seem to take Anvil's `@ContributesBinding` and `@ContributesMultibinding` to their logical conclusion:

    @get:ContributesMultibinding(AppScope::class)
    val superFun: GreatData = GreatData("FoolMe")

    @get:[ContributesBinding(AppScope::class) Named("TheGreatest")]
    val evenMoreFun: GreaterData = GreaterData("BarMe")

This does not seem possible at present (2.4.0-M2). My app modules have a lot of these, and often they're single-property modules. Annotating objects is supported, but instances of final classes are not.

**Comment by vRallev** [comment]
Yes, that's not possible and we don't intend to support that. These annotations are meant to bind a type, e.g. `Impl -> SuperType`. In your example there's no super type, e.g. 
```kotlin
@ContributesBinding(..)
object Abc
```
isn't supported either.
