### ISSUE TITLE
Resolving generic type parameter of superclass

### ISSUE THREAD

**Issue by romankivalin** [square/anvil#583]
Consider the following test case:
```kotlin
  @Test fun `type parameter of superclass is resolved`() {
    compile(
      """
      package com.squareup.test

      interface SomeClass1

      interface SomeClass2<T>

      interface SomeClass3 : SomeClass2<SomeClass1>
      """,
      allWarningsAsErrors = false,
      codeGenerators = listOf(
        simpleCodeGenerator { psiRef ->

          when (psiRef.shortName) {
            "SomeClass3" -> {
              assertThat(
                psiRef.directSuperClassReferences().single().typeParameters.single(). ???
              ).isEqualTo("com.squareup.test.SomeClass1")
            }
          }

          null
        }
      )
    ) {
      assertThat(exitCode).isEqualTo(OK)
    }
  }
```

`psiRef.directSuperClassReferences().single().typeParameters.single()` doesn't seem to contain information about the `SomeClass1`. `declaringClass` is `SomeClass2`, `upperBounds` is just `Any?`, and `psiRef.directSuperClassReferences().single().asTypeName()` is `SomeClass2<T>`.
How can I get the actual value of superclass type parameter?

**Comment by JoelWilcox** [comment]
Thanks for raising this @romankivalin. We have a private util method that does most of the work needed for this currently. I put up #584 as a potential fix.

**Comment by vRallev** [comment]
I left a comment in the proposal. @romankivalin please take a look as well.

**Comment by romankivalin** [comment]
Verified on snapshot version that #586 resolves the issue. `ClassReference.directSuperTypeReferences()` now returns `TypeReference`, which I can use to get type arguments.

**Comment by vRallev** [comment]
Wonderful!
