### ISSUE TITLE
Unresolved reference: Member injection in base Activity

### ISSUE THREAD

**Issue by aitorvs** [square/anvil#595]
When updating from `2.3.10-1-6-0` to `2.3.11-1-6-10` I started having unresolved reference errors for base activities member injections.

We would have the following

```kotlin
class MyActivity : BaseActivity() {...} 

class BaseActivity : AppCompatActivity() {
  @Inject lateinit var foo: Foo
  ...
}
```

That setup used to work but just upgrading to anvil `2.3.11-1-6-10` now results in `MyActivity_MembersInjector.kt: (39, 5): Unresolved reference: BaseActivity_MembersInjector`

**Comment by JoelWilcox** [comment]
Do you also see this issue on `2.4.0`?

**Comment by aitorvs** [comment]
> Do you also see this issue on `2.4.0`?

Yup, same with `2.4.0`. Do you know why this might be?

**Comment by vRallev** [comment]
Are you sure that `BaseActivity` is on the compile classpath and you enabled Anvil with the same version for this module?

**Comment by aitorvs** [comment]
Yup, nothing really changes in our codebase. Just updating anvil causes that error.

**Comment by vRallev** [comment]
Hard to say what going wrong. I assume you use an `implementation` dependency somewhere that should be an `api` dependency. Without a sample project there isn't much we could do.

**Comment by aitorvs** [comment]
But regardless, I guess it means something changed from `2.3.10` to `2.3.11`. Because just bumping the versions makes the build throw that error.

Just in case you want to take a look directly in our public repo:
* [this](https://github.com/duckduckgo/Android/tree/test/aitor/anvil_2311) is the branch with the anvil version bump
* just execute `./gradlew assembleID` in that one and `develop` to see how the version-bumped branch breaks the build

No need to, I understand is not as convenient as as a sample project. 
Will try to take a look at possible `implementation`s that may be at fault as well.

**Comment by vRallev** [comment]
I tried building your project, but it fails with
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonModelInternalDebug'.
> /Users/ralf/Development/projects/test/Android/app/CMakeLists.txt : C/C++ internalDebug|armeabi-v7a : CMake Error at /Users/ralf/Development/projects/test/Android/app/CMakeLists.txt:13 (add_library):
    Cannot find source file:

      src/main/cpp/third-party/bloom_cpp/src/BloomFilter.cpp

    Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
    .hxx .in .txx
```
So yes, we really need a sample.

**Comment by aitorvs** [comment]
> I tried building your project, but it fails with
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:generateJsonModelInternalDebug'.
> > /Users/ralf/Development/projects/test/Android/app/CMakeLists.txt : C/C++ internalDebug|armeabi-v7a : CMake Error at /Users/ralf/Development/projects/test/Android/app/CMakeLists.txt:13 (add_library):
>     Cannot find source file:
> 
>       src/main/cpp/third-party/bloom_cpp/src/BloomFilter.cpp
> 
>     Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>     .hxx .in .txx
> ```
> 
> So yes, we really need a sample.

We use submodules so probably you were missing `git submodule update --init`.

I was reading the changes in [2.3.11](https://github.com/square/anvil/releases/tag/v2.3.11) and none of them caught my as what could have changed that breaks this now. Do you have any idea?

**Comment by vRallev** [comment]
I looked at this again. You mis-use `api` and `implementation` dependencies quite a lot, but that's unrelated. 

You didn't configure Anvil or the Dagger annotation processor in modules that use member injection. That's why the classes were never generated in the first place. I didn't look into why it worked before, because the new behavior is the correct behavior. Your fix is here: https://github.com/duckduckgo/Android/commit/73f8b4bfa3d9e7a12c92a13407f5572cf4acde01

**Comment by vRallev** [comment]
@aitorvs Please let us know if you still think there's an issue.

**Comment by aitorvs** [comment]
> @aitorvs Please let us know if you still think there's an issue.

@vRallev Thanks a lot! That fixed the issue. Thanks a lot for taking the time to look at it. 

Unrelated, about the comment you made on abusing api and implementation deps. I agree, and I am very interested in knowing how do you generally go about that more holistically

**Comment by vRallev** [comment]
I suggest taking a look at the documentation: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation We try to follow it as good as we can. There are tools out there like https://github.com/RBusarow/ModuleCheck to automate the process, but we don't currently use them (yet).
