### ISSUE TITLE
@ContributesBinding with multi-component scope not working

### ISSUE THREAD

**Issue by bubenheimer** [square/anvil#596]
Anvil 2.4.0:

Given the following:

    @MergeComponent(ScopeA::class)
    @MergeComponent(ComboScope::class)
    interface ComponentA

    @MergeComponent(ScopeB::class)
    @MergeComponent(ComboScope::class)
    interface ComponentB

    @ContributesBinding(ComboScope::class, boundType = D::class)
    class C : D(), E, F

When I try to inject `D` somewhere within `ComponentA` or `ComponentB` Dagger compilation complains about the binding missing. This problem does not occur when I use individual `@ContributesBinding` annotations for `ScopeA` and `ScopeB` instead of the single `ComboScope` annotation. `ComboScope` also works fine in other contexts, just not in this particular `@ContributesBinding` case.

**Comment by vRallev** [comment]
I can reproduce the issue.
