### ISSUE TITLE
Kotlin 1.6.10 incremental compilation broken

### ISSUE THREAD

**Issue by Dkhusainov** [square/anvil#599]
Gradle: 7.2
Kotlin: 1.6.10
Anvil: 2.4.0

Adding `kotlin.incremental=false` to gradle.properties fixes the issue

Reproducer:
https://github.com/Dkhusainov/anvilbug

1. run `compileDebugKotlin` and see that `src-gen-debug` dir is not empty
2. change the body of function `A`
3. run `compileDebugKotlin`  and see that `src-gen-debug` dir is empty

**Comment by vRallev** [comment]
I can reproduce this, but it's not actual issue. The generated code will still end up in the binary. Look at `build/tmp/kotlin-classes/debug/anvil/...`. In there you'll find the generated hints as `.class` files. 

Did you run into actual compile issues?

**Comment by Dkhusainov** [comment]
After further investigation I found that the bug happens when using custom `CodeGenerator`s, where `projectFiles .classAndInnerClassReferences(module)` does not return all the types when invoked during incremental recompilation.

In updated sample `classAndInnerClassReferences`:
1. During full compilation returns 3 classes `Longs`, `Strings`, `b.Ints`, from which all the correct classes are generated
2. After that incremental recompilation with changed class `Longs` returns only `Longs` and classes generated during full compilation in step 1. `Strings` and `b.Ints` are absent and the code that would've been generated from them does not go into the final binary


Reproduce:
1. `clean`
2. `app:cDJWJ`
3. change `Longs`
4. `app:cDJWJ`
Note that steps 3 and 4 sometimes need to be repeated a second time to get the error

**Comment by vRallev** [comment]
I can reproduce the issue with your project. Interestingly, as soon as I try to attach the debugger the issue doesn't reproduce anymore. Unsure what's going on there. I see that the compiler provides only a single file in the `AnalysisHandlerExtension`. I verified this with log statements and a local Anvil build. I removed your custom code generator and still saw the issue.

I tried to reproduce the issue in the Anvil integration tests and wasn't able to do so. There the `AnalysisHandlerException` always provides all files. We've never seen this issue internally either. 

I have a hard time understanding what's going on, why it only happens in your project and nobody else reported this issue yet. Like I said, we haven't seen it either. Note that I filed a similar issue for the compiler in the past: https://youtrack.jetbrains.com/issue/KT-38570 For that particular issue we applied workarounds in Anvil's Gradle plugin. 

We probably need to debug the compiler. But like I mentioned above, with the debugger attached the issue doesn't reproduce. Very strange issue.

**Comment by Dkhusainov** [comment]
I've found that disabling `systemProp.kotlin.compiler.execution.strategy=in-process` Kotlin daemon fixes the issue. Maybe that's why running with debugging doesn't work - a new gradle process starts each time wiah a new daemon.
Anyway looks like a Kotlin bug, I'll file an issue to them.

**Comment by vRallev** [comment]
Please link the issue here as well.

**Comment by Dkhusainov** [comment]
https://youtrack.jetbrains.com/issue/KT-52060

**Comment by vRallev** [comment]
Given that this is a Kotlin problem I'm closing this issue.
