### ISSUE TITLE
`generateDaggerFactories = true` property access rights exceeded with 2.4.0

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#600]
Before 2.4.0 I used this with groovy gradle
```
anvil {
    generateDaggerFactories  true
}
```

Now with 2.4.0 that doesn't compile, so I used this

```
anvil {
    generateDaggerFactories = true
}
```

where lint (?) complains about the property visibility violated, so I'm not sure if it's working or not

<img width="733" alt="image" src="https://user-images.githubusercontent.com/1503402/164342439-75fbc262-5bfb-4166-900b-ed68647ea132.png">

**Comment by vRallev** [comment]
This is a false positive. You can safely ignore the warning, suppress it or call `generateDaggerFactories.set(true)`.
