### ISSUE TITLE
Issue with Multibindings

### ISSUE THREAD

**Issue by aitorvs** [square/anvil#63]
I am using Anvil + dagger multibindings to build a plugin system and I've encountered the following issue.

Consider the following setup (omitting the `AppComponent` for brevity)

```kotlin
interface PluginPoint<T> {
  fun getPlugins(): List<T>
}

interface PrinterPlugin {
  fun print()
}

@Module
@ContributesTo(AppScope::class)
class ExamplePluginsModule {

  @Provides
  @IntoSet
  fun provideFoo(): PrinterPlugin = Foo()

  @Provides
  @IntoSet
  fun provideBar(): PrinterPlugin = Bar()

}

class PrinterPluginPoint @Inject constructor(
  private val plugins: Set<PrinterPlugin>
): PluginPoint<PrinterPlugin> {
  override fun getPlugins(): List<PrinterPlugin> {
    return plugins.toList()
  }
}

class Foo: PrinterPlugin {
  override fun print() {
    Timber.d("Foo")
  }
}
class Bar: PrinterPlugin {
  override fun print() {
    Timber.d("Bar")
  }
}
```

Then in the Application class

```kotlin
open class App : HasAndroidInjector, Application() {
  //...

  @Inject
  lateinit var printerPluginPoint: PrinterPluginPoint

  override fun onCreate() {
    super.onCreate()

    // HERE configure DI...

    printerPluginPoint.getPlugins().forEach { it.print() }
  }

//...
}
```

Result: `[Dagger/MissingBinding] java.util.Set<? extends io.avs.android.plugins.PrinterPlugin>`

However, replacing the dependency of `PrinterPluginPoint` to a `Lazy<Set<PrinterPlugin>>` fixes the issue. I guess the codegen path is different

Is this known? or maybe I am missing something?

**Comment by vRallev** [comment]
Sounds like the module isn't merged. A sample project would certainly be helpful.

**Comment by aitorvs** [comment]
Sure thing. Will link a sample project, hopefully today

**Comment by aitorvs** [comment]
> Sounds like the module isn't merged. A sample project would certainly be helpful.

[Here it is](https://github.com/aitorvs/anvil-multibinding-sample.git)

**Comment by vRallev** [comment]
There's a bug in your code, it's unrelated to Anvil. Change the class to this and it works:
```
class PrinterPluginPoint @Inject constructor(
  private val plugins: Set<@JvmSuppressWildcards PrinterPlugin>
): PluginPoint<PrinterPlugin> {
  override fun getPlugins(): List<PrinterPlugin> {
    return plugins.toList()
  }
}
```

**Comment by aitorvs** [comment]
Sorry for the late response, thanks a lot!
Our of curiosity, do you happen to know why `Lazy` overcomes the issue with wildcards, without needing the annotation to suppress its generation?
