### ISSUE TITLE
AGP 7.3.0-rc01 and syncGeneratedSources=true not working

### ISSUE THREAD

**Issue by SteinerOk** [square/anvil#636]
Anvil configuration in my project:
```
plugins {
    id "com.squareup.anvil"
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        freeCompilerArgs += [
                "-opt-in=com.squareup.anvil.annotations.ExperimentalAnvilApi",
        ]
    }
}

anvil {
    syncGeneratedSources = true
}
```

After update to AGP 7.3.0-rc01 (Gradle 7.5.1) and related Android Studio version I received error, when try sync project: 
```
> Cannot convert the provided notation to a File or URI: [/Users/ihor/Documents/Projects/work-app-android/app/build/anvil/src-gen-paidGmsDebug].
  The following types/formats are supported:
    - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
    - A String or CharSequence URI, for example 'file:/usr/include'.
    - A File instance.
    - A Path instance.
    - A Directory instance.
    - A RegularFile instance.
    - A URI or URL instance.
    - A TextResource instance.
```

With AGP 7.2.2 all works fine.

**Comment by vRallev** [comment]
I tried it quickly in the Anvil project itself and couldn't reproduce the issue. Please provide a sample app.

**Comment by vRallev** [comment]
Any update on this?

**Comment by SteinerOk** [comment]
@vRallev , I will try tomorrow with new empty project and let you know

**Comment by SteinerOk** [comment]
@vRallev 
Sample project: [https://github.com/SteinerOk/AnvilTest](url), error screen: [https://postimg.cc/zHq11GyM](url)
Android studio: Dolphin (2021.3.1) RC 1
AGP: 7.3.0-rc01

**Comment by vRallev** [comment]
You might want to file a ticket for AGP, because I'm not seeing what Anvil is doing wrong. The error says:
```
The following types/formats are supported:
  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
  - A String or CharSequence URI, for example 'file:/usr/include'.
  - A File instance.
```
Anvil uses `File` as argument: https://github.com/square/anvil/blob/main/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt#L148-L153

Not sure what to do in this case.
