### ISSUE TITLE
Usage of absolute path as input

### ISSUE THREAD

**Issue by Tapchicoma** [square/anvil#65]
Recently after comparing build scans produced on developer machine and CI node we noticed following:
> Input 'kotlinCompile.com.squareup.anvil.compiler.src-gen-dir' is in both builds but the values are different.

This produces remote build cache misses for following tasks as paths are different:
- `org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask`
- `org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask`
- `org.jetbrains.kotlin.gradle.tasks.KotlinCompileWithWorkers`

I took a look in the source code and found this line: https://github.com/square/anvil/blob/9fb3c5f5b8a5134dd97d21d740271dcb276c6e0c/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt#L46 that returns absolute path to the Kotlin plugin. Kotlin plugin itself sets this as task inputs via https://github.com/JetBrains/kotlin/blob/34b55dbeb3a65b39b3585a646b5a0d2b1ce4dd96/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPlugin.kt#L1078

I am not sure what proper fix should be. Probably either using `srcGenDir.relativeTo(project.buildDir)` or asking Kotlin team to add relative `kind` type to [FilesSubpluginOptions](https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin-api/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinGradleSubplugin.kt#L36).

**Comment by vRallev** [comment]
Interestingly KSP [suffers from the same issue](https://github.com/android/kotlin/blob/ksp/libraries/tools/kotlin-ksp-gradle/src/main/kotlin/org/jetbrains/kotlin/ksp/gradle/KspSubplugin.kt#L53-L55). The challenge is to get the right root dir in the Kotlin compiler plugin itself.

**Comment by Tapchicoma** [comment]
I've updated to `2.0.1` version and still see values are different on CI and local builds. Probably fix is not working.

**Comment by vRallev** [comment]
Which values exactly? Is it the same path?

**Comment by Tapchicoma** [comment]
Yes, it is the same 'kotlinCompile.com.squareup.anvil.compiler.src-gen-dir'

**Comment by vRallev** [comment]
I double checked in our code base. That's the input value I see for this key `anvil/src-gen-compileDebugKotlin`. It's working fine for us.

**Comment by Tapchicoma** [comment]
will try to grab value for this key on Monday. What Kotlin version are you using? For us it is still `1.3.72`

**Comment by vRallev** [comment]
Same Kotlin version.

**Comment by Tapchicoma** [comment]
I've added following code for one of modules where I see cache miss:
```gradle
tasks.withType(org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask) {
    doLast {
        def prop = inputs.getProperties()
            .find { it.key == "kotlinCompile.com.squareup.anvil.compiler.src-gen-dir" }
        if (prop != null) {
            logger.warn("Input property '${prop.key}': ${prop.value} ")
        }
    }
}
```

On my machine it outputs following:
```
> Task :feature:html-resource-viewer:kaptGenerateStubsDebugKotlin
Input property 'kotlinCompile.com.squareup.anvil.compiler.src-gen-dir': /home/yahor/work/freeletics-android/feature/html-resource-viewer/build/anvil/src-gen-compileDebugKotlin
```

On CI node (that populates remote cache):
```
> Task :feature:html-resource-viewer:kaptGenerateStubsDebugKotlin
Input property 'kotlinCompile.com.squareup.anvil.compiler.src-gen-dir': /home/circleci/fl-application-android/feature/html-resource-viewer/build/anvil/src-gen-compileDebugKotlin
```

On the good side I don't see cache misses for `org.jetbrains.kotlin.gradle.tasks.KotlinCompileWithWorkers` tasks.

**Comment by vRallev** [comment]
I used this snippet:
```
gradle.taskGraph.afterTask { Task task ->
  if (task.name == 'compileKotlin') {
    task.inputs.properties.each { key, value ->
      if (key == 'com.squareup.anvil.compiler.src-gen-dir') {
        println "Input: $key $value"
      }
    }
  }
}
```
There I couldn't see the absolute paths anymore. Now that you don't see the cache misses either anymore this seems to be fixed. Or is anything else missing?

**Comment by vRallev** [comment]
Ah, I see. Let me take a look.

**Comment by vRallev** [comment]
I see what's going on:
```
> Task :sample:library:kaptKotlin UP-TO-DATE
Input: kotlinCompile.com.squareup.anvil.compiler.src-gen-dir anvil/src-gen-compileKotlin

> Task :sample:library:compileKotlin UP-TO-DATE
Input: com.squareup.anvil.compiler.src-gen-dir anvil/src-gen-compileKotlin

> Task :sample:app:kaptDebugKotlin
Input: kotlinCompile.com.squareup.anvil.compiler.src-gen-dir anvil/src-gen-compileDebugKotlin

> Task :sample:app:compileDebugKotlin
Input: com.squareup.anvil.compiler.src-gen-dir anvil/src-gen-compileDebugKotlin
```
The Kotlin plugin seems to copy inputs from the compilation task to the inputs of the Kapt task. Notice the prefix `kotlinCompile.`.

**Comment by gabrielittner** [comment]
`KaptWithoutKotlincTask` is fixed in 2.0.5 from a quick check. However `KaptGenerateStubsTask` still has an issue. I noticed it has 2 inputs and one them still has absolute paths:

```
Input: com.squareup.anvil.compiler.src-gen-dir anvil/src-gen-compileProductionApiReleaseUnitTestKotlin
Input: kotlinCompile.com.squareup.anvil.compiler.src-gen-dir /Users/gabriel/work/freeletics/app/freeletics/build/anvil/src-gen-compileStagingApiDebugKotlin
```

**Comment by vRallev** [comment]
I see this now, too. I wonder what changed or why I missed that earlier.

**Comment by runningcode** [comment]
I'm going to stick this in the ticket so it doesn't get lost in the pull request. :)
I would recommend writing a cache relocatability test to ensure that all the tasks are relocatable.

Here is a sample in groovy:
https://github.com/gradle/android-cache-fix-gradle-plugin/blob/master/src/test/groovy/org/gradle/android/CrossVersionOutcomeAndRelocationTest.groovy#L32

Here is a sample in kotlin:
https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/build-system/integration-test/application/src/test/java/com/android/build/gradle/integration/cacheability/CacheabilityTest.kt#181

**Comment by vRallev** [comment]
I appreciate the link, but it's not very useful. Setting up projects in tests for Gradle is tedious. There's so much more code involved than the linked test classes.

**Comment by vRallev** [comment]
Oh, I see. This happens only with Kotlin `1.3.72` and not with Kotlin `1.4.10` anymore. @gabrielittner can you confirm that you're still on Kotlin 1.3?

**Comment by vRallev** [comment]
The hacky workarounds that I have to avoid this issue don't seem to work with Kotlin 1.3. I'm not sure why. Since Kotlin 1.4 is already out I stop looking for a solution. I've added a check in #132 that hopefully prevents that this issue happens again with Kotlin 1.4.

**Comment by Tapchicoma** [comment]
@vRallev we are using Kotlin 1.4.10

**Comment by gabrielittner** [comment]
When I tested it last week it was on 1.4.0

**Comment by Tapchicoma** [comment]
@gabrielittner I've checked on 1.4.10 - same issue

**Comment by vRallev** [comment]
Got it. Then it must be related to the Kotlin version that is used for compiling this project, because I'm not seeing any problems when I change this project to use Kotlin 1.4.

**Comment by h0tk3y** [comment]
From what I see, this would be indeed a valid use case for other `FilesOptionKind` values in `FilesSubpluginOption`.

**Comment by vRallev** [comment]
Thanks @h0tk3y, that was the missing piece of the puzzle.
