### ISSUE TITLE
Compiler doesn't pick incremental changes to multibindings

### ISSUE THREAD

**Issue by sergei-lapin** [square/anvil#657]
There seems to be an issue with incremental changes: in my use case compiler doesn't generate binding methods for new multibinding contributions.

**Use case**:
1. Compile app
2. Contribute new dependency to multibinding
3. Compile app

**Expected result**:
Anvil module has binding method for new dependency

**Actual result**:
It doesn't

**Steps to reproduce**:
1. Checkout https://github.com/sergei-lapin/napt/tree/anvil-reproducer
2. Run `./gradlew :sample-kotlin-lib:assemble`
3. Uncomment `SomeDepImpl2` in `Impl2.kt`
4. Run `./gradlew :sample-kotlin-lib:assemble`

**Comment by vRallev** [comment]
I tested your sample project and it fails with Napt. If you switch your project to Kapt instead, then everything works properly. The Anvil Gradle plugin applies some workarounds to make incremental compilation work: https://github.com/square/anvil/blob/main/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt#L232-L255

**Comment by vRallev** [comment]
Due to the incremental compilation the compiler can decide to not recompile certain files, because it "knows" that changes don't impact these files. But that's not true for the way Anvil works when merging classes.
