### ISSUE TITLE
Anvil Not picking up `internal` functions in a public module.

### ISSUE THREAD

**Issue by agrosner** [square/anvil#659]
Working on migrating a heavy dagger implementation into Anvil and we have many modules with `public` module with `internal` functions. When using `generateDaggerFactories = true` , the code generated does not recognize `internal` visibility:
```
'public' function exposes its 'internal' return type CardRowLayoutFactory
```

`CardRowLayoutFactory` is `internal`, its function in the module is `internal`:
```kotlin
  @Binds
  @IntoMap
  @LayoutKey(CardRowDataModel::class)
  internal abstract fun cardRowLayout(cardRowLayoutFactory: CardRowLayoutFactory): LayoutFactory
```

I know that `internal` modules are not supported by Anvil, but `internal` functions, are they not?

**Comment by vRallev** [comment]
I have mixed feelings about this. There are opportunities to add more checks, but on the other hand we can't predict usage. E.g. you `internal` binds method might be valid, if this Dagger module is only used within the same module. There are also options to make the `internal` visibility modifier more flexible, see [here](https://youtrack.jetbrains.com/issue/KTIJ-7662/IDE-support-internal-visibility-introduced-by-associated-compilations). So I rather leave it up to the compiler to verify these checks.
