### ISSUE TITLE
Remove workaround that disables `usePreciseJavaTracking` with Kotlin 1.8 support

### ISSUE THREAD

**Issue by vRallev** [square/anvil#670]
The issue [KT-38576](https://youtrack.jetbrains.com/issue/KT-38576) has been resolved with Kotlin 1.8 and the workaround is no longer needed. When Anvil drops support for Kotlin 1.7 it should also remove this workaround.

**Comment by ZacSweers** [comment]
Could it remove the workaround if running in a kotlin 1.8 setup?

**Comment by vRallev** [comment]
Absolutely!

**Comment by midery** [comment]
Hey! That is a great news! 
Anvil has an other workaround that [disables incremental kapt stubs generation](https://github.com/square/anvil/blob/main/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt#L118). Could it also be removed, or is it used to deal with another problem?

**Comment by vRallev** [comment]
Yes, that solves a different problem and still is required.

**Comment by midery** [comment]
Thanks for your reply! I assume that stated problem is [described here](https://github.com/square/anvil#incremental-kotlin-compilation-breaks-compiler-plugins), but Kotlin issue's status is "Fixed" in 1.8.0. 

Disabling incremental compilation for kapt in our codebase makes huge performance drawback on incremental builds, so it'll be really great if you could provide some details.

**Comment by vRallev** [comment]
The README got a little out of date. I'm addressing this here: https://github.com/square/anvil/pull/685 I'm sorry about the confusion.

**Comment by midery** [comment]
Great! Thanks a lot for clarification.
