### ISSUE TITLE
Kotlin 1.7 Support

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/anvil#677]
Anvil 2.4.4 was just released with the statement:
> Remove support for Kotlin 1.7. Anvil only supports Kotlin 1.8 moving forward.

It would be really great if anvil could at least continue to support the latest kotlin version that’s supported by compose stable (currently 17.2.0)

**Comment by vRallev** [comment]
You can keep using the old version. There's nothing wrong with that. New development only happens with the latest stable version. Supporting both was overhead for us.
