### ISSUE TITLE
Allow configuration of KotlinCompiler used in AnvilCompilation to set jvm target

### ISSUE THREAD

**Issue by devPalacio** [square/anvil#682]
Hi there,
I just upgraded a project to target java 11 and I have a unit test for a custom annotation which uses the internal `compileAnvil` method.

https://github.com/square/anvil/blob/4b925f7b50e330acafa396e239a03bcf7858671a/compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt#L193
The JVM target is hard-coded to target 1.8 and when I run the test it fails with the following error:

`Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option`

Would it be possible to allow the user to configure the JVM target for the `compileAnvil` method?

**Comment by vRallev** [comment]
Sounds very reasonable!
