### ISSUE TITLE
Component merging appears to be broken in Kotlin 1.8.20-Beta with kapt IR enabled

### ISSUE THREAD

**Issue by ZacSweers** [square/anvil#688]
Repro: https://github.com/slackhq/circuit/pull/454

While nothing appears to fail from Anvil itself, component merging appears not to succeed as Dagger complains during kapt about missing the `@Component` annotation that anvil would normally add during stub generation.

```
> Task :samples:star:kaptReleaseKotlin FAILED
/Users/zacsweers/dev/slack/oss/circuit/samples/star/build/tmp/kapt3/stubs/release/com/slack/circuit/star/di/AppComponent.java:29: error: @Component.Factory types must be nested within a @Component
    public static abstract interface Factory {

```

**Comment by vRallev** [comment]
https://youtrack.jetbrains.com/issue/KT-56635/

**Comment by JoelWilcox** [comment]
Closing since it looks like this is resolved now
