### ISSUE TITLE
Provide SingleIn and AppScope as part of Anvil

### ISSUE THREAD

**Issue by gabrielittner** [square/anvil#692]
It might not fit 100% but I think it would help with standardization in the community instead of each project defining their slightly different own variant of this. Especially `SingleIn` fits really well with Anvil's other annotations from a code style perspective.

**Comment by vRallev** [comment]
After setting up Anvil in another repository than Square's, I changed my mind a little bit and I'm more open to this change now. It could be a guiding force to a better DI setup. @JoelWilcox and @ZacSweers, I'm curious to hear your opinion?

**Comment by ZacSweers** [comment]
SingleIn makes sense, I don't think appscope makes sense (anvil isn't just for Android apps). I do kinda think it's a bit orthogonal to anvil though, maybe better as just another open source project?

**Comment by vRallev** [comment]
Yes, a separate artifact makes sense. I wouldn't create a separate project. I'd probably add `@ForScope` too (it's just a Dagger qualifier `@ForScope(AppScope::class)`.

**Comment by gabrielittner** [comment]
Sounds good to me. I agree that AppScope is more specific, it would be nice to have but the 2 annotations would already be great

**Comment by JoelWilcox** [comment]
A separate artifact sounds reasonable to me 👍 (and I agree with excluding `AppScope`). Maybe something like `:annotations-optional`?

**Comment by vRallev** [comment]
The advantage of adding `AppScope` is that it can be shared wildly, similar to `@Singleton`. Imagine a third party library wanting to contribute something to the `AppScope`. It can't if every app use a different `AppScope` class. On the other hand, if they all reuse the same `AppScope` class, then this wouldn't be a problem.

Counter argument to my own argument: `@MergeComponent` is repeatable and you could simple do this:
```
@MergeComponent(com.abc.AppScope::class)
@MergeComponent(com.other.AppScope::class)
interface AppComponent
```

**Comment by Dkhusainov** [comment]
> Yes, a separate artifact makes sense. I wouldn't create a separate project. I'd probably add `@ForScope` too (it's just a Dagger qualifier `@ForScope(AppScope::class)`).

Consider adding generic `@Typed(MyType::class)`(similar to `@Named` but type instead of string) annotation instead of semantic `@ScopeIn(MyScope::class)`.

**Comment by ZacSweers** [comment]
`@Typed(MyType::class)` is far less readable. I think it's better to take an opinionated `ForScope` as it conveys that the intent is to use it with something like anvil's scope keys

**Comment by gabrielittner** [comment]
I've opened a pr that based on this discussion adds `SingleIn` and `ForScope` as a separate artifact but leaves out `AppScope`.
