### ISSUE TITLE
2.4.4 Dagger compatibility

### ISSUE THREAD

**Issue by Dkhusainov** [square/anvil#698]
I upgraded my project  `2.4.2` -> `2.4.4` and the dagger compiler stopped compiling with this error:
`method is missing parameters for required modules or components`. It wasn't picking up `object` modules with `@Provides` methods.

Turns out anvil `2.4.4.` requires Dagger `2.44+`(mine was `2.42`) to work. Should probably include this in changelog.

**Comment by ZacSweers** [comment]
This is vague and it's hard to speculate where the problem is without more information

**Comment by JoelWilcox** [comment]
@Dkhusainov are you still experiencing an issue or able to provide more details?

**Comment by ZacSweers** [comment]
I think this can be closed. Changelog mention makes sense

**Comment by JoelWilcox** [comment]
Added a note to the 2.4.4 release notes for any future folks that may run into this.
