### ISSUE TITLE
AssistedFactoryGenerator error with KotlinPoet 1.13.0

### ISSUE THREAD

**Issue by SteinerOk** [square/anvil#699]
Disclaimer: I'm not sure if this is the right place to create a bug, but since I only have an anvil error from the logs, I'll take a chance.

I'm using anvil to generate Dagger Factories (`generateDaggerFactories = true`) in a library module.
Additionally, I use custom generators.

Now I started getting this error:
```
Back-end (JVM) Internal error: The parameters in the factory method must match the @Assisted parameters in com.example.lib.HomeWorker.
```
Full log: [click](https://gist.github.com/SteinerOk/d0ba276f19a24e7171e77c39c416761b)
In this situation, the problem arose precisely after updating KotlinPoet to version 1.13.0
On version 1.12.0 everything works fine

Additionally:
The custom generator ([click](https://github.com/SteinerOk/sealant/blob/main/work-codegen/src/main/java/dev/steinerok/sealant/work/generator/WorkerCreationGenerator.kt)) uses the annotation and creates an `@AssistedFactory` interface by inheriting from [this](https://github.com/SteinerOk/sealant/blob/main/work-api/src/main/java/dev/steinerok/sealant/work/WorkerAssistedFactory.kt) from which the already standard `AssistedFactoryGenerator` generates a factory

Sample project: https://github.com/SteinerOk/anvil-kp-bug

**Comment by JoelWilcox** [comment]
Should be fixed by https://github.com/square/anvil/pull/700
