### ISSUE TITLE
Custom code generator does not get called when just changing the parent of a class

### ISSUE THREAD

**Issue by matejdro** [square/anvil#708]
Steps to reproduce:

1. Download [Archive.zip](https://github.com/square/anvil/files/11485500/Archive.zip)
2. Run `./gradlew assembleDebug` - build should pass
3. Open `app/src/java/com/matejdro/anvildemo/MyClass.kt` and change parent from `ClassA` to `ClassB`
4. Run `./gradlew assembleDebug` - build will fail, complaining that `MyClassModule` does not exist (it was not generated)

**Comment by ZacSweers** [comment]
This is a dupe of #693

**Comment by JoelWilcox** [comment]
@matejdro can you provide a branch link instead of a zip file? I'm initially inclined to agree this sounds very similar to #693 but from the description it sounds like there are no annotation argument changes involved?

**Comment by matejdro** [comment]
Here you go: https://github.com/matejdro/issues/tree/anvil-ic-parent-change

**Comment by matejdro** [comment]
This seems fixed by `v2.5.0-beta01` with `trackSourceFiles` on and custom code generator update to `GeneratedFileWithSources`d :tada:
