### ISSUE TITLE
Anvil cannot contribute more than one subcomponent to a single scope

### ISSUE THREAD

**Issue by matejdro** [square/anvil#709]
It seems like every subcomponent generated by `@ContributesSubcomponent` generates `createFactory()` for that subcomponent that is then implemented by the parent component.

However, this breaks down if more than one subcomponent is contributed. Then parent component would have multiple `createFactory()` methods with same signature, but different return type, resulting in a Dagger error:

```
/home/matej/Downloads/Archive/app/build/tmp/kapt3/stubs/debug/com/matejdro/anvildemo/AppComponent.java:6: error: Found conflicting entry point declarations. Getter methods on the component with the same name and signature must be for the same binding key since the generated component can only implement the method once. Found:
public abstract interface AppComponent extends anvil.component.com.matejdro.anvildemo.appcomponent.FirstSubcomponentA.ParentComponent, anvil.component.com.matejdro.anvildemo.appcomponent.SecondSubcomponentA.ParentComponent {
                ^
      @org.jetbrains.annotations.NotNull anvil.component.com.matejdro.anvildemo.appcomponent.FirstSubcomponentA.SubcomponentFactory anvil.component.com.matejdro.anvildemo.appcomponent.FirstSubcomponentA.ParentComponent.createFactory()
      @org.jetbrains.annotations.NotNull anvil.component.com.matejdro.anvildemo.appcomponent.SecondSubcomponentA.SubcomponentFactory anvil.component.com.matejdro.anvildemo.appcomponent.SecondSubcomponentA.ParentComponent.createFactory()
```

Steps to reproduce:

1. Download [Archive.zip](https://github.com/square/anvil/files/11504874/Archive.zip)
2. Run `./gradlew assembleDebug`

**Comment by dmytroKarataiev** [comment]
You can contribute as many subcomponents to a single scope as you want as long as you give your factory-providing functions unique names: 
`createFirstSubcomponentAFactory` and `createSecondSubcomponentAFactory`

**Comment by matejdro** [comment]
But these factory providing functions are generated by Anvil, I can't edit them manually.

**Comment by matejdro** [comment]
As far as I can tell, name of this method has no bearing on final generated method by Anvil. You can try it with the project attached to the first post.

**Comment by dmytroKarataiev** [comment]
> As far as I can tell, name of this method has no bearing on final generated method by Anvil. You can try it with the project attached to the first post.

```
It's strongly recommended creating a parent component interface next to the factory that is contributed to the parent scope. The parent component interface should have one method that returns the factory type, e.g.
```

Here's what it should look like in your repo (btw, use GitHub, that way, I could've sent you a PR with working code):

```
package com.matejdro.anvildemo

import com.squareup.anvil.annotations.ContributesSubcomponent
import com.squareup.anvil.annotations.ContributesTo

@ContributesSubcomponent(
    scope = FirstSubcomponentScope::class,
    parentScope = AppScope::class,
)
interface FirstSubcomponent {

    @ContributesSubcomponent.Factory
    interface Factory {

        fun create(): FirstSubcomponent
    }

    @ContributesTo(AppScope::class)
    interface Parent {

        fun createFirst(): Factory
    }
}

class FirstSubcomponentScope

```

and second:

```
package com.matejdro.anvildemo

import com.squareup.anvil.annotations.ContributesSubcomponent
import com.squareup.anvil.annotations.ContributesTo

@ContributesSubcomponent(
    scope = SecondSubcomponentScope::class,
    parentScope = AppScope::class,
)
interface SecondSubcomponent {

    @ContributesSubcomponent.Factory
    interface Factory {

        fun create(): SecondSubcomponent
    }

    @ContributesTo(AppScope::class)
    interface Parent {

        fun createSecond(): Factory
    }
}

class SecondSubcomponentScope

```

**Comment by matejdro** [comment]
> Here's what it should look like in your repo (btw, use GitHub, that way, I could've sent you a PR with working code

You are right, I was a bit lazy, uploading a zip was just easier.

> It's strongly recommended creating a parent component interface next to the factory that is contributed to the parent scope. The parent component interface should have one method that returns the factory type, e.g.

Doh, I totally missed that in documentation. Thanks a lot for your help!
