### ISSUE TITLE
Anvil 2.4.5 does not pick up new files with Multibindings

### ISSUE THREAD

**Issue by matejdro** [square/anvil#710]
Steps to reproduce:

1. Download and open [Project.zip](https://github.com/square/anvil/files/11543822/Project.zip)
2. Run project
3. Note that logs/activity will print two entries (as it should)
4. Completely delete LibraryMultibinds.kt
5. Run again and check logs/activity
6. Logs/activity will now show only a single entry, as it should
7. Re-add LibraryMultibinds.kt
8. Run project
9. Note that Logs/activity still show only a single entry. Clean build fixes the issue.

This seems similar to the #693, however, I believe it is a different issue:

* Not related to the annotations changes, it happens when adding completely new files from scratch
* `kaptGenerateStubsDebugKotlin` gets executed normally in step 8, so it is not `UP-TO-DATE` issue
* It happens regardless of the `kotlin.incremental.useClasspathSnapshot` flag setting
* This seems to be a regression with Anvil 2.4.5 (or more likely Kotlin 1.8.2X)
* None of the workarounds from the #693 thread seem to work

This is pretty serious issue since it requires clean build when every single new file using multibindings is added to the project.

Might be related to the #707 and #708

**Comment by tujhex** [comment]
I have this problem on my project, seems that it's related directly to Anvil, because when I downgraded anvil to `2.4.4` all works fine again. PS: also I disabled new IR backend with `kapt.use.jvm.ir=false`, because it breaks dagger in strange manner

**Comment by tujhex** [comment]
A little note: with Anvil  `2.4.5`/`2.4.6`, kotlin `1.8.21` and `kapt.use.jvm.ir=false` it's broken (dagger components not generated)

**Comment by ZacSweers** [comment]
This is a dupe of #693

**Comment by matejdro** [comment]
Can you explain why this is a dupe? I've made a list in the ticket on why I believe this is not a dupe.

**Comment by ZacSweers** [comment]
The IC issue is not dependent on the new IC being enabled, it's just exacerbated by it. I think it's a distraction to treat all these IC related issues as independent and better to combine their details in one place (where someone that works on it is already active).

**Comment by matejdro** [comment]
I would agree if those issues had seemingly same cause, but while they are all related to IC (and have similar outcomes), it seems that this one has a completely different cause because it happens in completely different circumstances.

**Comment by matejdro** [comment]
Here is a reproducing branch instead of a zip file: https://github.com/matejdro/issues/tree/anvil-ic-new-file

**Comment by matejdro** [comment]
This seems fixed by `v2.5.0-beta01` with `trackSourceFiles` on

**Comment by JoelWilcox** [comment]
Thanks for updating @matejdro ! It's helpful to get confirmation that things are working while we're testing out the new changes :)

**Comment by RBusarow** [comment]
Excellent!
