### ISSUE TITLE
Annotation with `@MapKey(unwrapValue = false)` ("complex map key") doesn't support explicit API mode

### ISSUE THREAD

**Issue by bddckr** [square/anvil#735]
The source that `MapKeyCreatorGenerator` generates is missing an explicit return type, giving this error message:
```
Return type must be specified in explicit API mode
```

I'm interested in contributing a fix (along with additional tests) and will be raising a PR in a few minutes. 😃

**Comment by vRallev** [comment]
Thanks!

**Comment by bddckr** [comment]
@vRallev I've force-pushed changes to the PR to fix the failed checks. Could you please approve the workflow run on the PR so I can see whether all checks are fine now? (I've validated it locally, but you never know 😅)
