### ISSUE TITLE
Configuration error in gradle-plugin when building on Windows

### ISSUE THREAD

**Issue by apramana** [square/anvil#744]
Out of curiosity I tried building the branch @JoelWilcox was using to debug KSP. I couldn't repro the issue CI is facing, but I ran into this error when using Powershell:

```
Could not get unknown property 'libs' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

It goes away if I import the version catalog using [this](https://docs.gradle.org/current/userguide/platforms.html#sec:importing-catalog-from-file) approach. Is there any reason not to use this approach instead of symlink-ing the wrapper in gradle-plugin? (If not, I can put up a PR to fix it.)

**Comment by JoelWilcox** [comment]
IIRC when this came up previously the main reason we wanted to keep the symlink was to not need to manage multiple gradle wrappers. Were you able to identify any other alternatives that resolved the error for you?
