### ISSUE TITLE
Support KSP in factory generation

### ISSUE THREAD

**Issue by ZacSweers** [square/anvil#751]
This issue is to track KSP support in factory gen, and different from #704

- [x] AnvilMergeAnnotationDetectorCheck.kt #756
- [x] AssistedFactoryGenerator.kt #795
- [x] AssistedInjectGenerator.kt #795
- [ ] BindsMethodValidator.kt
- [x] ComponentDetectorCheck.kt #753
- [x] InjectConstructorFactoryGenerator.kt #795
- [x] MapKeyCreatorGenerator.kt #788
- [x] MembersInjectorGenerator.kt #795
- [x] ProvidesMethodFactoryGenerator.kt #806
- [x] ContributesMultibinding #740
- [x] ContributesTo #742
- [x] AnvilAnnotationDetectorCheck #722
- [x] ContributesBinding #722
- [x] BindingModuleGenerator #877
- [x] ContributesSubcomponentGenerator #828

**Comment by jhperezd** [comment]
👋 I'll be taking `ComponentDetectorCheck.kt` and `AnvilMergeAnnotationDetectorCheck.kt` to begin with.

**Comment by r0adkll** [comment]
👋🏻 I'll be taking `MembersInjectorGenerator.kt` to start with as well

**Comment by jhperezd** [comment]
👋 PRs for `ComponentDetectorCheck.kt` (https://github.com/square/anvil/pull/753) and `AnvilMergeAnnotationDetectorCheck.kt` (https://github.com/square/anvil/pull/756) are up. I'll take `InjectConstructorFactoryGenerator.kt` next.

**Comment by ursusursus** [comment]
May I ask?

Is this about not having to use

```
anvil {
  generateDaggerFactories = true // default is false
}
```
such that one would then use `ksp dagger` everywhere instead, therefore avoiding the incremental compiliation issue?

**Comment by ZacSweers** [comment]
That wouldn't be enough as you still need anvil's hint generation for contributed elements

**Comment by IlyaGulya** [comment]
@ZacSweers 
Hello!
Would you accept help from the community to speed up this issue resolution?

**Comment by ZacSweers** [comment]
Sure! The last two are gnarly, so it make take a bigger lift. I can write up more about them tomorrow

**Comment by ZacSweers** [comment]
So the main issue is that both of those generates require doing class scanning, which complicates things in KSP due to it processing nodes that are not in the compilation source set.

This is obviously necessary for module/component merging, but ideally shouldn't be necessary for any of the factory generators.

**BindingModuleGenerator**

This is the one that requires the most change. Currently Anvil will scan within the package and generate _one_ module for all the contributed bindings. This is a greedy aggregating step, and after some discussion with @vRallev we agreed this should be simplified to just generate 1:1 mappings of a `@ContributesBinding` class to a generated `@ContributesTo`-annotated binding module, rather than one aggregated one. This refactoring would affect both the existing Anvil PSI support as well as KSP.

The bulk of the work would be to adopt this new model, then implement dual KSP support afterward.

**ContributesSubcomponentHandlerGenerator and ContributesSubcomponentGenerator**

This is support for `@ContributesSubcomponent`, which is a fairly involved case and requires doing class scanning. I _think_ `ContributesSubcomponentHandlerGenerator` can be saved for the dagger-KSP PR as it deals with merging, and ContributesSubcomponentGenerator is just a simple generator. I've updated the task list to remove `ContributesSubcomponentHandlerGenerator` now that I've looked at it more.

**Comment by ZacSweers** [comment]
I'm gonna take ContributesSubcomponentGenerator next since it's trivial

**Comment by ZacSweers** [comment]
`BindsMethodValidator` should be a simple one to do. There is also a bug with the current implementation in PSI (#750) that may get fixed by KSP since it has built-in assignability checks

**Comment by IlyaGulya** [comment]
> `BindsMethodValidator` should be a simple one to do. There is also a bug with the current implementation in PSI (#750) that may get fixed by KSP since it has built-in assignability APIs

Thanks!
Then, I'll take `BindsMethodValidator`.

**Comment by ZacSweers** [comment]
👍

**Comment by IlyaGulya** [comment]
@ZacSweers Is there anything that should be done? I can take another task if there's one 🙂

**Comment by ZacSweers** [comment]
The last big one will be `BindingModuleGenerator`. But in this case, anvil needs to change how this works and no longer merge modules to create one large module. Instead, binding module hints need to be updated to generate 1:1 binding -> binding module to simplify things. If you want to tackle that that would be helpful, but you may need more guidance from @vRallev and @JoelWilcox on how that implementation should look. This change would need to work in Embedded too

**Comment by ZacSweers** [comment]
@IlyaGulya fyi I've actually started working on `BindingModuleGenerator` after some discussion with the square folks and Ralf

**Comment by gildor** [comment]
Does #831 merge means that all points are done now. Maybe there are some other follow-up tasks to follow.
Thanks!

**Comment by ZacSweers** [comment]
yup!
