### ISSUE TITLE
Component Factories and Builders

### ISSUE THREAD

**Issue by abyrnes** [square/anvil#77]
I'm wondering if there should be documentation around how anvil works with `@Component.Factory` and `@Component.Builder`.

Without anvil, you'll get the following compiler error from dagger if you attempt to use either annotation on an interface whose containing interface isn't annotated with `@Component`:
```
@Component.Factory types must be nested within a @Component
```

So it may seem a bit odd when using anvil since the compiler plugin adds the `@Component` annotation, making it perfectly legal to do something dagger explicitly guards against.

Thoughts?

**Comment by vRallev** [comment]
We don't use component factories. Would this be correct?
```
@MergeComponent(...)
interface MyComponent {

   @Component.Factory
   interface Factory {
    
   }
 }
```
I tried to make it clear that the `@MergeComponent` annotation adds the `@Component` annotation for you. What would you change?

**Comment by abyrnes** [comment]
That's correct, yea. Unfortunately, I don't think there's really anything that you can change. It was more of just an observation that it's a behavior I find to be a little weird on the surface. One of the first things I did when reading through the documentation was notice a lack of documentation on builders and factories, making me wonder if they worked at all, although I admittedly missed the part where the `@Component` annotation is added by the plugin.

I think it could be useful to some to elaborate on anvil's behavior as it pertains to factories and builders in the documentation.

I'd be happy to put something together if you think it's worthwhile. Otherwise we can close the issue.

**Comment by vRallev** [comment]
I tried to encapsulate this in the very first example where I say "this is what you write" and "this is what Dagger sees" https://github.com/square/anvil#anvil

**Comment by abyrnes** [comment]
Yup. As I said my only concern is anvil permitting users to write code dagger prohibits.

I don't think any further action is needed. Maybe if it comes up again as the library gains traction it can be revisited

**Comment by vRallev** [comment]
Sounds fair. Thanks for bringing it up nonetheless.
