### ISSUE TITLE
Factory generation: private typealias

### ISSUE THREAD

**Issue by Dkhusainov** [square/anvil#81]
```
import javax.inject.Inject

private typealias Foo = MyClassFoo

class MyClassFoo

class MyClass @Inject constructor(foo: Foo)
```

Error:
```
Cannot access 'Foo': it is private in file
```

**Comment by vRallev** [comment]
You expose the private typealias on a public constructor. Notice how the IDE also suggests to use type `Foo`. 
![image](https://user-images.githubusercontent.com/1558045/91650418-3f55ad80-ea34-11ea-8b40-13cde3b0d33a.png)

The code is very misleading. This won't be fixed in Anvil.
