### ISSUE TITLE
Factory generation: unncecessary private imports

### ISSUE THREAD

**Issue by Dkhusainov** [square/anvil#82]
```
package com.example.myapplication

import javax.inject.Inject
import com.example.myapplication.MyClass.Result.*

class MyClass @Inject constructor() {

  private sealed class Result {
    class Some : Result()
    class Other : Result()
  }

  private fun some(): Result = Some()
  private fun other(): Result = Other()
}
```

Generated factory contains unnecessary(for compilation) import `import com.example.myapplication.MyClass.Result.*`, which fails to compile.

**Comment by vRallev** [comment]
The compiler plugin uses the Psi API. For performance reasons it doesn't resolve all types and doesn't resolve all imports properly. As a workaround it inherits all imports from the origin file even though they might be unused. This is also necessary to work around issues with star imports.
