### ISSUE TITLE
Factory generation: support factory generation for classes without @Inject annotation when return type is not explicetly set

### ISSUE THREAD

**Issue by Tapchicoma** [square/anvil#86]
For example we have following module:
```kotlin
@Module
object RxSchedulersModule {
    @Provides
    @RxIOScheduler
    fun provideIOScheduler() = Schedulers.io()
}
```

Anvil currently will not generate any factory for this case. To fix it I need to add explicit return type to `provideIOScheduler()` method.

**Comment by vRallev** [comment]
This "limitation" won't change. It's bad practice to rely on implicit return types. Imagine `Schedulers.io()` would change the return type. You suddenly would see confusing Dagger errors.

The other reason is that this Anvil feature works with the Psi APIs. During compilation that happens before types are resolved. It cannot infer the return type without resolving them.
